pkg/controller/framework_test.go, pkg/controller/snapshot_controller.go, pkg/controller/snapshot_controller_base.go
As we say https://github.com/xing-yang/external-snapshotter/pull/10#pullrequestreview-148119074
=> remove class store since we donot update it in controller

pkg/connection/connection.go, pkg/connection/connection_test.go, pkg/controller/csi_handler.go, pkg/controller/framework_test.go, pkg/controller/snapshot_controller.go
This PR fixed the issue of not updating the snapshot restore size after
snapshot is created. Before snapshot is ready, the returned size might
not be accurate. So we need to keep updating the snapshot size during
checking the snapshot status.
=> Fix updating restore size issue

deploy/kubernetes/setup-csi-snapshotter.yaml, examples/kubernetes/pvc.yaml, examples/kubernetes/restore.yaml, examples/kubernetes/snapshot.yaml, examples/kubernetes/snapshotclass.yaml, examples/kubernetes/storageclass.yaml
This PR adds example yaml files for deployment and testing of the snapshot feature.
Images will be updated when they are released.
=> Add example yaml files for deployment and testing

pkg/apis/volumesnapshot/v1alpha1/types.go, pkg/apis/volumesnapshot/v1alpha1/zz_generated.deepcopy.go, pkg/controller/framework_test.go, pkg/controller/snapshot_controller.go, pkg/controller/snapshot_create_test.go
Change the restore size to int64 for snapshot content. Also add the code
to update the restore size for snapshot content.
=> Fix restore size type in snapshot content

pkg/controller/framework_test.go, pkg/controller/snapshot_controller.go, pkg/controller/snapshot_controller_base.go, pkg/controller/snapshot_delete_test.go, pkg/controller/snapshot_ready_test.go
In VolumeSnapshotContent, if the CSI driver does not match the plugin's,
the controller should skip this content instead of always processing it.
This PR also add a few tests related to snapshot and content static
binding.
During binding, if content specify its bound snapshot uid and it
does not match the snapshot's uid, the content object and also the
physical snapshot will be deleted. In this case, the controller will
treat the content as an orphan content because its snapshot object does
not exist (deleted) any more.
=> Handle the CSI driver in VolumeSnapshotContent does not match case

Makefile, cmd/csi-snapshotter/main.go
This PR updates version in the Makefile based on "git describe".
Also updates main.go to show version.
=> Update version in the Makefile

README.md, deploy/kubernetes/README.md, deploy/kubernetes/rbac-external-provisioner.yaml, deploy/kubernetes/rbac.yaml, deploy/kubernetes/setup-csi-snapshotter.yaml
Splitting out the RBAC definitions into a separate file has the
advantage that it can be used as-is without editing in other
deployments. For example, the kubernetes-csi/docs example can
use this rbac.yaml file instead of a local copy.
=> deploy: split out RBAC definitions

pkg/controller/util.go
If content name is already in snapshot object, just use it.
This may be the case for static provisioning. Otherwise construct
new name for content for dynamic provisioning.
=> Use existing content name

pkg/apis/volumesnapshot/v1alpha1/types.go, pkg/controller/framework_test.go, pkg/controller/snapshot_controller.go
This PR renames Ready to ReadyToUse in VolumeSnapshot Status
to be consistent with the name in CSI spec.
This should be added to the release note.
=> Rename Ready to ReadyToUse

cmd/csi-snapshotter/main.go, pkg/controller/framework_test.go, pkg/controller/snapshot_controller.go, pkg/controller/snapshot_controller_base.go, pkg/controller/snapshot_create_test.go
fix https://github.com/kubernetes-csi/external-snapshotter/issues/70
@xing-yang @jingxu97
=> add pvcLister to snapshot controller

cmd/csi-snapshotter/main.go, pkg/controller/framework_test.go, pkg/controller/snapshot_controller.go, pkg/controller/snapshot_controller_base.go, pkg/controller/snapshot_create_test.go
Reverts kubernetes-csi/external-snapshotter#72
PR #72 caused a hang when creating a snapshot.  As a result, the snapshot was never created.  Need to revert it.
=> Revert "add pvcLister to snapshot controller"

pkg/controller/csi_handler.go, pkg/controller/snapshot_controller.go, pkg/controller/snapshot_create_test.go, pkg/controller/util.go, pkg/controller/util_test.go
This PR adds new reserved prefixed parameter keys which are stripped
out of parameter list, and adds deprecation notice for old keys and
keep their behavior the same.
```
csiParameterPrefix = "csi.storage.k8s.io/"
prefixedSnapshotterSecretNameKey      = csiParameterPrefix + "snapshotter-secret-name"
prefixedSnapshotterSecretNamespaceKey = csiParameterPrefix + "snapshotter-secret-namespace"
```
This fix is modeled after a similar fix in external-provisioner: https://github.com/kubernetes-csi/external-provisioner/pull/178 
/assign @davidz627 @jingxu97 @saad-ali @msau42
=> Add new reserved prefixed parameter keys

pkg/connection/connection_test.go, pkg/controller/framework_test.go, pkg/controller/snapshot_controller.go, pkg/controller/util.go, pkg/controller/util_test.go
=> Correct error variables and fix other golint errors.

Dockerfile
Reason: k8s core components move its base images to distroless/static. See kubernetes/kubernetes#70249 (comment) for details.
=> Use distroless as base image

cmd/csi-snapshotter/main.go
There is no reason why driver name should not be used as snapshotter name.
It only confuses people and adds unnecessary redundancy.
=> Deprecate --snapshotter option

Gopkg.lock, Gopkg.toml, vendor/k8s.io/api/Godeps/Godeps.json, vendor/k8s.io/apiextensions-apiserver/Godeps/Godeps.json, vendor/k8s.io/apiextensions-apiserver/OWNERS, vendor/k8s.io/apimachinery/Godeps/Godeps.json, vendor/k8s.io/apimachinery/pkg/util/proxy/upgradeaware.go, vendor/k8s.io/client-go/.travis.yml, vendor/k8s.io/client-go/CHANGELOG.md, vendor/k8s.io/client-go/Godeps/Godeps.json, vendor/k8s.io/client-go/README.md, vendor/k8s.io/client-go/rest/config.go, vendor/k8s.io/client-go/rest/config_test.go, vendor/k8s.io/client-go/tools/clientcmd/client_config.go, vendor/k8s.io/client-go/tools/clientcmd/client_config_test.go, vendor/k8s.io/client-go/transport/config.go, vendor/k8s.io/client-go/transport/round_trippers.go, vendor/k8s.io/client-go/transport/token_source.go, vendor/k8s.io/client-go/transport/token_source_test.go
Update dependencies to k8s 1.13.1 based on the release-1.0 branch.
This is a temporary branch to test with kubebuilder as the latest kubebuilder release depends on k8s 1.13.1.
=> Update dependencies to k8s 1.13.1 from the release-1.0 branch

cmd/csi-snapshotter/main.go
Following up on https://github.com/kubernetes-csi/external-snapshotter/pull/92#issuecomment-463705342 to add operation timeout flag. 
/assign @msau42 @xing-yang
=> add csi timeout flag

pkg/controller/snapshot_controller.go
Instead of using PVC's storage class name, which might be nil, use the one we discovered before.
=> Use discovered storageclassName to look up the storage class

CHANGELOG-1.1.md
This PR adds a change log for the v1.1 release.
Fixes #
```release-note
NONE
```
=> Add change log for v1.1

cmd/csi-snapshotter/main.go
/kind bug
This PR fixes the help message for the default CSI timeout to 1 minute.
Fixes #
```release-note
NONE
```
=> Fix the default timeout in help msg

deploy/kubernetes/setup-csi-snapshotter.yaml
/kind bug
This PR updates deployment images to v1.1.0.
Fixes #
```release-note
NONE
```
=> Update deployment images to v1.1.0

CHANGELOG-1.2.md
This adds a changelog for v1.2.
Fixes #
```release-note
NONE
```
=> Add changelog for v1.2

deploy/kubernetes/rbac.yaml
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Set secret rbac as optional.
Some drivers may require a secret while some don't.
By default, we should give less permission as possible because `ClusterRole` is quite a broad.
Other sidecars like external-provisioner and external-attacher have comment out that. It should be ok to do it in external-snapshotter.
ref https://kubernetes-csi.github.io/docs/secrets-and-credentials.html#secret-rbac-rules
related issue …
=> minimize rbac permission by setting secrets as optional

cmd/csi-snapshotter/main.go
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
connectionTimeout is deprecated in favor of csiTimeout, logging connectionTimeout won't look good as this doesn't have any effect in NewSnapshotter.
Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>
Fixes #
```release-note
None
```
=> log csiTimeout will while starting snapshotter

cmd/csi-snapshotter/main.go
/kind bug
CSI has many controllers with leader election functionality. It's best to disambiguate between all the different locks used for LE
Fixes #128 
```release-note
Add a prefix "external-snapshotter-leader" and the driver name to the snapshotter leader election lock name.
```
=> Leader election lock name should include driver name

pkg/snapshotter/snapshotter.go, pkg/snapshotter/snapshotter_test.go
/kind bug
This PR introduces a check to see if ListSnapshot is supported before calling it GetSnapshotStatus.
If ListSnapshot is not supported, we just return that the snapshot is ReadyToUse and no creation time/restore time.
Fixes #132
n/a
```release-note
Snapshotter will no longer call ListSnapshots if the CSI Driver does not support this operation. 
```
=> Check if ListSnapshot is supported during GetSnapshotStatus

release-tools/build.make, release-tools/prow.sh, release-tools/travis.yml
We want to support testing under Kubernetes 1.15 and need updated rules for that. This PR also fixes the problem that the current rules reference a 1.14 deployment of "canary" images, which became problematic when making incompatible changes in the hostpath driver (driver name change).
See https://github.com/kubernetes-csi/external-provisioner/pull/313
```release-note
NONE
```
=> Prow update

pkg/snapshotter/snapshotter.go, pkg/snapshotter/snapshotter_test.go
/kind bug
Cherry-picks a fix where external snaphotter fails in prebound snapshot case with a driver
that does not support `ListSnapshots` request.
Release 1.2 doesn't have the fix in the master. 
This is a cherry-pick from master.
```release-note
Cherry picks PR #138: Prebound snapshots will work correctly with CSI drivers that does not support ListSnasphots.
```
=> Cherry-pick: Check if ListSnapshots is supported during GetSnapshotStatus

pkg/controller/framework_test.go, pkg/controller/snapshot_controller.go, pkg/controller/snapshot_controller_test.go, pkg/controller/snapshot_create_test.go, pkg/controller/snapshot_delete_test.go, pkg/controller/snapshot_ready_test.go, pkg/controller/util.go, pkg/controller/util_test.go
/kind feature
This PR adds deletion secret as annotation to volume snapshot content.
It also disallows annotation in template for snapshotter-secret-name.
Fixes #161 #155 
```release-note
Adds deletion secret as annotation to volume snapshot content.
```
=> Add deletion secret as annotation to content

cmd/csi-snapshotter/main.go
* This will exit the sidecar container when its gRPC connection to the CSI driver is lost. When a CSI driver goes down, we do not want the sidecar container on that node to still be leader.
Fixes #
```release-note
We will now exit the external-snapshotter when the connection to a CSI driver is lost, allowing for another leader to takeover.
```
=> Exit on CSI gRPC conn loss

pkg/controller/framework_test.go, pkg/controller/snapshot_controller.go, pkg/controller/snapshot_create_test.go, pkg/controller/snapshot_ready_test.go
/kind bug
Fixed checking of binding of PVC when creating snapshots.
Fixes #
```release-note
Added extra verification of source PersistentVolumeClaim before creating snapshot.
```
=> Verify PV/PVC binding and driver

pkg/controller/framework_test.go, pkg/controller/snapshot_controller.go, pkg/controller/snapshot_create_test.go, pkg/controller/snapshot_ready_test.go
Backport PV/PVC binding change (https://github.com/kubernetes-csi/external-snapshotter/pull/172) to release-1.2 branch.
Note: Resolved merge conflicts in pkg/controller/snapshot_create_test.go.
/kind bug
Fixed checking of binding of PVC when creating snapshots.
Fixes #
```release-note
Added extra verification of source PersistentVolumeClaim before creating snapshot.
```
=> Cherry-pick: Verify PV/PVC binding and driver

CHANGELOG-1.2.md, pkg/controller/framework_test.go, pkg/controller/snapshot_controller.go, pkg/controller/snapshot_create_test.go, pkg/controller/snapshot_ready_test.go
This PR modifies the change log for 1.2.2 release.
Fixes #
```release-note
NONE
```
=> Change log 1.2.2

pkg/controller/framework_test.go, pkg/controller/snapshot_controller.go, pkg/controller/snapshot_create_test.go, pkg/controller/snapshot_ready_test.go
Backport PV/PVC binding change (#172) to release-1.0 branch.
Note: Resolved merge conflicts in the following files:
pkg/controller/snapshot_controller.go
pkg/controller/snapshot_create_test.go
/kind bug
Fixed checking of binding of PVC when creating snapshots.
Fixes #
```release-note
Cherry pick PR #172: Added extra verification of source PersistentVolumeClaim before creating snapshot.
```
=> Cherry-pick to 1.0: Verify PV/PVC binding and driver

CHANGELOG-1.0.md
Fixes #
```release-note
NONE
```
=> Add changelog for v1.0.2

Makefile, pkg/controller/framework_test.go, pkg/controller/snapshot_controller.go, pkg/controller/snapshot_create_test.go, pkg/controller/snapshot_ready_test.go
Backport PV/PVC binding change (#172) to release-0.4 branch.
Manually resolved conflicts in the following files:
pkg/controller/snapshot_controller.go
pkg/controller/snapshot_create_test.go
pkg/controller/snapshot_ready_test.go
/kind bug
Fixed checking of binding of PVC when creating snapshots.
Fixes #
```release-note
Cherry pick PR #172: Added extra verification of source PersistentVolumeClaim before creating snapshot.
```
=> Cherry-pick to 0.4: Verify PV/PVC binding and driver

.prow.sh
We have chicken and egg problems between external-snapshotter and hostpath csi driver as we're moving snapshots from alpha to beta and making changes in the way snapshots is deployed. So this PR temporarily disables other tests until the snapshot beta API PR is merged.
This PR disable all other tests except the unit tests until
the snapshot beta API PR is merged.
Fixes #
```release-note
NONE
```
=> Run only unit tests for now

CHANGELOG-0.4.md
This PR adds changelog for v0.4.2.
Fixes #
```release-note
NONE
```
=> Add changelog for v0.4.2

pkg/sidecar-controller/content_create_test.go, pkg/sidecar-controller/framework_test.go, pkg/sidecar-controller/snapshot_controller_test.go, pkg/sidecar-controller/snapshot_delete_test.go, pkg/sidecar-controller/snapshot_finalizer_test.go
/kind cleanup
Adds unit tests to sidecar-controller
```release-note
NONE
```
=> Add sidecar-controller unit tests

pkg/sidecar-controller/snapshot_controller_test.go
Adds more test coverage to the sidecar-controller package
Part of #204 
```release-note
NONE
```
=> Add tests for shouldDelete function

pkg/sidecar-controller/content_create_test.go, pkg/sidecar-controller/framework_test.go, pkg/sidecar-controller/snapshot_controller.go, pkg/sidecar-controller/snapshot_delete_test.go, pkg/utils/util.go
/kind cleanup
/kind bug
clean up sidecar logic, fix potential snapshot leaking issue, added more test cases
Fixes #209 
NONE
```release-note
None
```
=> sidecar controller update, fix potential snapshot leaking

cmd/snapshot-controller/main.go, pkg/common-controller/framework_test.go, pkg/common-controller/snapshot_controller.go, pkg/common-controller/snapshot_controller_base.go
/kind cleanup
Removes createSnapshotContentRetryCount and createSnapshotContentInterval
from command line options.
Fixes #
This was brought up during the review of the README PR (https://github.com/kubernetes-csi/external-snapshotter/pull/206) that these parameters should just be internal variables, not command line options.
```release-note
Removes createSnapshotContentRetryCount and createSnapshotContentInterval
from command line options.
```
=> Remove createSnapshotContentRetryCount and createSnapshotContentInterval

README.md
This PR adds a warning message in the upgrade process that the underlying snapshots will be deleted.
Fixes #
```release-note
NOTE
```
=> Add a warning msg in the upgrade process

pkg/common-controller/snapshot_controller.go
/kind bug
The err for updateSnapshotStatus was being defined locally (shadowed)
Fixes #
```release-note
NONE
```
=> Fix err shadow in updateSnapshotStatus and add retry delay

pkg/common-controller/snapshot_controller.go, pkg/utils/util.go
/kind cleanup
This PR updates the snapshot controller logic.
Fixes #
```release-note
NONE
```
=> Update snapshot controller

deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml, deploy/kubernetes/snapshot-controller/rbac-snapshot-controller.yaml, deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
/kind cleanup
Remove "sidecar" language for the controller.
Update image tag to 2.0.0-rc4 (the latest)
```release-note
NONE
```
=> Small fixes to snapshot-controller YAML

pkg/sidecar-controller/snapshot_controller.go
/kind bug
This PR stops calling CSI CreateSnapshot when ReadyToUse is already true in VolumeSnapshotContent status.
Fixes #223 
```release-note
NONE
```
=> Stop calling CreateSnapshot when ReadyToUse is true

README.md, cmd/csi-snapshotter/main.go
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
=> Fix typo in readme

pkg/common-controller/snapshot_controller.go
PVC Finalizer is intended to prevent PVC from being deleted when there is a snapshot actively being created from it.  After the snapshot is created successfully and in ReadyToUse status, and if there are no other snapshots actively being created from this PVC, the PVC finalizer should be removed.
This is a bug introduced by the latest code refactoring. Without this fix, the current code only removes the PVC finalizer when the snapshot has a deletionTimestamp.  The fix here is to move the code that removes the PVC finalizer outside of the function that handles the snapshot with a deletionTimestamp in syncSnapshot().  This way PVC finalizer will always be removed when it is not needed actively as a source.
/kind bug …
=> Remove PVC finalizer when no longer in use

CHANGELOG-1.3.md, CHANGELOG-2.0.md
Add changelog for release 2.0.
Also removes changelog for 1.3 as we don't have a 1.3 release.
Fixes #
```release-note
NONE
```
=> Add changelog for release 2.0

CHANGELOG-2.0.md
This PR adds changelog for 2.0.1 release.
Fixes #
```release-note
NONE
```
=> Add changelog for 2.0.1 release

pkg/common-controller/framework_test.go, pkg/common-controller/snapshot_delete_test.go, pkg/common-controller/snapshot_update_test.go
/kind cleanup
refactor finalizer-specific test to use withSnapshotFinalizers function
Fixes #253 
Part of #196 
n/a
```release-note
NONE
```
=> Refactor common controller tests to use withXYZ functions and add tests

config/crd/snapshot.storage.k8s.io_volumesnapshotclasses.yaml, config/crd/snapshot.storage.k8s.io_volumesnapshotcontents.yaml, config/crd/snapshot.storage.k8s.io_volumesnapshots.yaml, hack/update-crd.sh, pkg/apis/volumesnapshot/v1beta1/types.go
/kind bug
Includes additional information for the `get` command for the VolumeSnapshot* CRDs.
Fixes #247
```release-note
Prints additional details when using kubectl get on VolumeSnapshot, VolumeSnapshotContent, and VolumeSnapshotClass API objects.
```
=> Update CRDs to include additional get information

pkg/common-controller/snapshot_controller.go, pkg/common-controller/snapshot_update_test.go
/kind bug
This PR adds VolumeSnapshotBeingDeleted annotation to the VolumeSnapshotContent object before the finalizers on the VolumeSnapshot object is removed. This is to make sure that the annotation is on the Content before VolumeSnapshot object is removed from the API server.
Fixes #248 
```release-note
NONE
```
=> Add VolumeSnapshotBeingDeleted annotation to content

pkg/common-controller/framework_test.go, pkg/common-controller/snapshot_controller.go, pkg/common-controller/snapshot_create_test.go, pkg/common-controller/snapshot_delete_test.go, pkg/common-controller/snapshot_update_test.go
/kind cleanup
Adds more tests, and fixes a few bugs I found.
Fixes #196 
* I uncommented all commented tests, fixed them, and added additional ones where needed.
* code cov for snapshot_controller.go is now 82.9%, up from 74% previously.
* broke up the tests & bug fixes into separate commits
```release-note
NONE
```
=> Fix error propagation in checkandAddSnapshotFinalizers and add tests

pkg/sidecar-controller/content_create_test.go, pkg/sidecar-controller/framework_test.go, pkg/sidecar-controller/snapshot_controller.go, pkg/sidecar-controller/snapshot_delete_test.go
/kind cleanup
Fixes #267 
n/a
```release-note
NONE
```
=> Add more sidecar tests and cleanup sidecar code

pkg/common-controller/snapshot_controller.go
/kind bug
It's currently possible for the snapshotController to crash when checking snapshot Finalizers if the VolumeSnapshotContent is nil. This PR introduces a simple nil check to prevent the panic.
```release-note
NONE
```
=> Include a nil check for the snapshotContent

pkg/common-controller/snapshot_controller.go, pkg/common-controller/snapshot_controller_base.go, pkg/common-controller/snapshot_create_test.go, pkg/common-controller/snapshot_update_test.go, pkg/common-controller/snapshotclass_test.go
/kind flake
There were some instances where a namespace remained after a test due to a VolumeSnapshot persisted after the associated objects (VolumeSnapshotContent/PVC) and VolumeSnapshotClass had been deleted. If the cluster entered into this state, then the namespace would remain until the VolumeSnapshot was manually removed.
This PR allows a VolumeSnapshot that's been scheduled for deletion to be successfully deleted if the VolumeSnapshotClass cannot be found.
N/A
```release-note
NONE
```
=> Allows VolumeSnapshot to be deleted if the class isn't found

pkg/common-controller/snapshot_controller.go
/kind bug
Moves the nil check on VolumeSnapshotContent to the correct location.
```release-note
NONE
```
=> Moving nil check to correct location

hack/README.md
****What type of PR is this?**
Add missing workaround to hack/update-generated-code.sh
Fixes #239
As per reviewer's request https://github.com/kubernetes-csi/external-snapshotter/issues/239#issuecomment-577985400, added the steps to let users to use update-generated-code.sh..
```release-note
NONE
```
=> doc: add workaround for hack/update-generated-code.sh

cmd/csi-snapshotter/main.go, cmd/snapshot-controller/main.go
/kind feature
Adjusts the worker threads to be configurable for the snapshot-controller and csi-snapshotter.
Fixes #276 
```release-note
The number of worker threads in the snapshot-controller and csi-snapshotter is now configurable via the `worker-threads` flag.
```
=> Makes the number of worker threads configurable.

CHANGELOG-2.1.md, README.md
Fixes #
Waiting for PR #261 to be merged.
```release-note
NONE
```
=> Changelog for 2.1 release

.prow.sh
/kind cleanup
snapshotter pull jobs were misleading and not actually running the k8s e2e tests.
Fixes #
```release-note
NONE
```
=> Re-enable k8s e2e tests in pull jobs

.prow.sh, release-tools/SIDECAR_RELEASE_PROCESS.md, release-tools/build.make, release-tools/prow.sh
/kind cleanup
Cherry-pick of https://github.com/kubernetes-csi/external-snapshotter/pull/301 and https://github.com/kubernetes-csi/external-snapshotter/pull/298
Updates csi-release-tools to latest to pick up snapshotter e2e fixes, and re-enable k8s e2e tests.
Fixes #
```release-note
NONE
```
=> Cherry pick of #298, #301: Re-enable k8s e2e tests

README.md, cmd/csi-snapshotter/main.go, cmd/snapshot-controller/main.go, pkg/common-controller/snapshotclass_test.go
Fix typos.
Fixes #
```release-note
NONE
```
=> Nit: fix typos

pkg/common-controller/snapshot_controller.go, pkg/common-controller/snapshot_create_test.go
Signed-off-by: zhuc <zhucan.k8s@gmail.com>
Need to add an event on the VolumeSnapshot API object after we've created VolumeSnapshotContent in the common controller
Fixes #268 
@xing-yang 
```release-note
Add event for snapshotting in progress
```
=> Add event for snapshotting in progress

pkg/sidecar-controller/framework_test.go, pkg/sidecar-controller/snapshot_controller.go, pkg/sidecar-controller/snapshot_controller_base.go, pkg/sidecar-controller/snapshot_delete_test.go
/kind bug
Add requeue to the sidecar controller.
Part of #225
```release-note
This fixes the re-queue logic so a failed snapshot operation will be added back to a rate limited queue for retries.
```
=> Fix the requeue logic

go.mod, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go, v2/pkg/metrics/metrics.go, v2/pkg/metrics/metrics_test.go
/kind feature
This PR is to provide basic metrics utilities which later could be used in common controller for end to end operation metrics recording.
Fixes #142 
This PR only contains the basic metrics utility functions needed for end to end operational metrics recording in snapshot controller. Another PR will be based on this to add metrics recording in snapshot controller code. ATM, it should NOT have any user-facing changes.
```release-note
Adds the basic metrics utility functions needed for end to end operational metrics recording in snapshot controller.
```
=> add metric to common controller - basic metrics utilities

.cloudbuild.sh, cloudbuild.yaml, cmd/csi-snapshotter/Dockerfile, cmd/snapshot-controller/Dockerfile, release-tools/SIDECAR_RELEASE_PROCESS.md, release-tools/build.make, release-tools/cloudbuild.sh, release-tools/cloudbuild.yaml, release-tools/prow.sh
This updates release-tools and then enables cloud image
building in commit 8e680b17.
Commit summary for csi-release-tools:
bd416901 cloud build: initial set of shared files
6f2322e8 Update patch release notes generation command
```release-note
publishing of images on k8s.gcr.io
```
=> master: update release-tools, enable cloud build

pkg/sidecar-controller/content_create_test.go, pkg/sidecar-controller/snapshot_controller.go, pkg/sidecar-controller/snapshot_delete_test.go
/kind flake
Allows the sidecar to delete VolumeSnapshots if the VolumeSnapshotClass has already been deleted. This PR is a followup to https://github.com/kubernetes-csi/external-snapshotter/pull/275 for the sidecar.
Fixes #264 
```release-note
Allows the sidecar to delete volume snapshots if the volume snapshot class is not found.
```
=> Updated sidecar to not require VolumeSnapshotClass for snapshot deletion

pkg/common-controller/framework_test.go, pkg/common-controller/snapshot_controller.go, pkg/common-controller/snapshot_update_test.go
/kind bug
This PR updates the Error field in the snapshot status based on the status of the content.
Partial fix for #333
```release-note
Updates Error field in the snapshot status based on the status of the content.
```
=> Update Error in Snapshot Status

pkg/common-controller/framework_test.go, pkg/common-controller/snapshot_controller.go, pkg/common-controller/snapshot_update_test.go
Irrespective of any error on the Volume Snapshot
object, initiate dynamic VolumeSnapshotContent object
creation. If any required parameters are not found, (e.g. missing
VS class), the VS content object creation would fail gracefully.
/kind bug
Recover from intermittent  errors in VolumeSnapshot object
Fixes #333 
```release-note
Recover from intermittent errors in VolumeSnapshot object
```
=> Call dynamic VS content creation unconditionally

cmd/csi-snapshotter/main.go, cmd/snapshot-controller/main.go
/kind bug
This PR uses a separate client for leader election. In case of throttling of API server due to snapshot controller, leader election routine will remain unaffected. 
Fixes #343
```release-note
Use a separate API server client for leader election.
```
=> Use separate client for leader election

pkg/common-controller/snapshot_controller.go, pkg/sidecar-controller/snapshot_controller.go
/kind bug
This PR moves the event up so event will be emitted even if snapshot/content status update fails so user can see the error.
Fixes #346 
```release-note
Emit event even if status update fails.
```
=> Emit event even if status update fails

release-tools/SIDECAR_RELEASE_PROCESS.md, release-tools/travis.yml
Commit summary:
82d108ac switch to Go 1.15
843bddca Add steps on promoting release images
```release-note
build with Go 1.15
```
=> master: update release-tools

pkg/common-controller/framework_test.go, pkg/common-controller/snapshot_controller.go
/kind bug
Fixes #349 
```release-note
Fix a problem deleting the PVC finalizer and snapshot finalizer.
```
=> Fix the race between PVC finalizer and snapshot finalizer removal

client/config/crd/snapshot.storage.k8s.io_volumesnapshotclasses.yaml, client/config/crd/snapshot.storage.k8s.io_volumesnapshotcontents.yaml, client/config/crd/snapshot.storage.k8s.io_volumesnapshots.yaml, client/hack/README.md, client/hack/update-crd.sh
Signed-off-by: prateekpandey14 <prateekpandey14@gmail.com>
>
> /kind bug
> /kind design
> /kind flake
Update the volume snapshot CRDs to `apiextensions.k8s.io/v1`.
FYI as per kubernetes/kubernetes#82022 (comment) removal of `apiextensions.k8s.io/v1beta1` has been targeted for 1.22
Fixes #364 
```release-note
Update volume snapshot CRDs to apiextensions.k8s.io/v1 version
```
=> Update volume snapshot CRDs to v1 version

deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml, deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml, deploy/kubernetes/webhook-example/README.md, deploy/kubernetes/webhook-example/admission-configuration-template, deploy/kubernetes/webhook-example/create-cert.sh, deploy/kubernetes/webhook-example/webhook.yaml
/kind cleanup
The image name for the webhook was wrong in the example.
Also fixed a few nitpicks
```release-note
NONE
```
=> Fix image name for example webhook, and other nitpicks

pkg/common-controller/framework_test.go, pkg/common-controller/snapshot_controller_base.go, pkg/common-controller/snapshotclass_test.go
`checkAndUpdateSnapshotClass` must always return a snapshot, even though it fails somewhere in  `ctrl.SetDefaultSnapshotClass` - `syncSnapshotByKey` panics with nil return. I tried to fix `syncSnapshotByKey` to allow nil return, but the resulting code was just ugly.
While the real fix is one-liner in snapshot_controller_base.go, the PR is bigger due to test refactoring - `testCall` must have an opportunity to return a "fatal" error, even though a "normal" error is expected.
/kind bug
```release-note
Fixed crash of snapshot-controller when source PVC of a snapshot to take does not exist.
```
Fixes: #380
=> Fix panic when source PVC does not exist

release-tools/SIDECAR_RELEASE_PROCESS.md, release-tools/build.make, release-tools/cloudbuild.sh, release-tools/cloudbuild.yaml, release-tools/filter-junit.go, release-tools/prow.sh, release-tools/travis.yml
/kind cleanup
Updates the release tools to latest upstream
Fixes #385 
n/a
```release-note
NONE
```
=> release-2.1: Update release tools for go build fix

cmd/csi-snapshotter/Dockerfile, cmd/snapshot-controller/Dockerfile, cmd/snapshot-validation-webhook/Dockerfile
/kind bug
**What this PR does / why we need it**: As distroless image is now multiarch, image push job fails on s390x and ppc64le due to lack of support.
Fixes # https://github.com/kubernetes-csi/csi-release-tools/issues/105
**Special notes for your reviewer**: Workaround to allow builds to pass while we add support to distroless image.
**Does this PR introduce a user-facing change?**: 
```release-note
Changing distroless base image from multiarch to -amd64 to fix Prow builds
```
=> Fix the failing multiarch builds

cmd/csi-snapshotter/main.go, pkg/sidecar-controller/content_create_test.go, pkg/sidecar-controller/csi_handler.go, pkg/sidecar-controller/framework_test.go, pkg/sidecar-controller/snapshot_controller.go, pkg/sidecar-controller/snapshot_controller_base.go, pkg/utils/util.go, pkg/utils/util_test.go
@msau42 @xing-yang @Madhu-1 
/kind feature
This PR introduces an `--extra-create-metadata` flag to the CSI snapshotter.
When set to true, the VolumeSnapshot's name / namespace and the VolumeSnapshotContent's name will be passed as parameters to the CSI driver in `CreateSnapshotRequest`.
Fixes #341
In the CSI provisioner we have a `csi.storage.k8s.io/` prefix defined for metadata passed as parameters to the CSI driver:
https://github.com/kubernetes-csi/external-provisioner/blob/b1d315e4b8dbc7e4a948ee2b9b3d7a58892cfa57/pkg/controller/controller.go#L108-L111
I want to use this same prefix in the CSI snapshotter for consistency, however in this repo this …
=> Pass snapshot metadata to CSI driver

cmd/csi-snapshotter/Dockerfile, cmd/snapshot-controller/Dockerfile, cmd/snapshot-validation-webhook/Dockerfile
>
/kind bug
> /kind design
> /kind flake
**What this PR does / why we need it**: Support for s390x/ppc64le has been added to distroless static/base images and hence the Dockerfiles can go back to using multiarch images.
Fixes # https://github.com/kubernetes-csi/csi-release-tools/issues/105
```release-note
Changing distroless image back to multiarch
```
=> Revert to multiarch distroless base image

README.md
This PR adds instructions on setting up resource quotas for VolumeSnapshot CRS
Fixes #382 
```release-note
```
=> add instructions on creating volume snapshot quota for CRs

pkg/common-controller/snapshot_controller.go
/kind bug
Currently there's a timing issue in `createSnapshotContent` which does not proceed if a PVC is marked for deletion, irrespective of whether the PVCFinalizer already exists on the PVC. 
The result is that the PVC will remain in Terminating state and VolumeSnapshot.ReadyToUse will be false infinitely. 
```
$ kubectl get pvc -A
NAMESPACE               NAME       STATUS        VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                                                   AGE
csi-mock-volumes-6032   test-pvc   Terminating   pvc-d2b09880-89ea-42a0-9896-c1159b35f349   2Gi        RWO            csi-mock-volumes-6032-csi-mock-csi-mock-volumes-6032-scczwbv   4m
$ kubectl get …
```
=> Allow creation of snapshot content if pvc finalizer exists, even if pvc is marked for deletion.

CHANGELOG/CHANGELOG-3.0.md, pkg/common-controller/framework_test.go, pkg/common-controller/snapshot_controller_base.go, pkg/common-controller/snapshotclass_test.go
/kind bug
Cherry-pick from https://github.com/kubernetes-csi/external-snapshotter/pull/381
Fixes #
```release-note
Cherry-pick from https://github.com/kubernetes-csi/external-snapshotter/pull/381. Fixed crash of snapshot-controller when source PVC of a snapshot to take does not exist.
```
=> Cherry-pick the fix for panic when source PVC does not exist

pkg/sidecar-controller/snapshot_controller.go, pkg/sidecar-controller/snapshot_delete_test.go
/kind bug
If a CSIDriver requires credentials, but the VolumeSnapshotClass has been deleted, then the VolumeSnapshotContent cannot be deleted even though it contains a reference to the credentials in its own annotations.
This PR grabs the credentials instead of checking to see if the VolumeSnapshotClass exists, so that we can delete VolumeSnapshotContent objects if the secret annotation is on the VolumeSnapshotContent.
Fixes #412
```release-note
NONE
```
=> Get credentials before checking if the SnapshotClass exists

deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml, deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
currently, image pull policy is set to Always, if the pod restarts the image will be always pulled even if its present, changing
the pull policy will speed up the pod creation.
Fixes #
```release-note
None
```
=> change image pullpolicy from Always to IfNotPresent

go.mod, pkg/validation-webhook/certwatcher.go, pkg/validation-webhook/webhook.go, pkg/validation-webhook/webhook_test.go, vendor/github.com/fsnotify/fsnotify/.editorconfig, vendor/github.com/fsnotify/fsnotify/.gitattributes, vendor/github.com/fsnotify/fsnotify/.gitignore, vendor/github.com/fsnotify/fsnotify/.travis.yml, vendor/github.com/fsnotify/fsnotify/AUTHORS, vendor/github.com/fsnotify/fsnotify/CHANGELOG.md, vendor/github.com/fsnotify/fsnotify/CONTRIBUTING.md, vendor/github.com/fsnotify/fsnotify/LICENSE, vendor/github.com/fsnotify/fsnotify/README.md, vendor/github.com/fsnotify/fsnotify/fen.go, vendor/github.com/fsnotify/fsnotify/fsnotify.go, vendor/github.com/fsnotify/fsnotify/go.mod, vendor/github.com/fsnotify/fsnotify/go.sum, vendor/github.com/fsnotify/fsnotify/inotify.go, vendor/github.com/fsnotify/fsnotify/inotify_poller.go, vendor/github.com/fsnotify/fsnotify/kqueue.go, vendor/github.com/fsnotify/fsnotify/open_mode_bsd.go, vendor/github.com/fsnotify/fsnotify/open_mode_darwin.go, vendor/github.com/fsnotify/fsnotify/windows.go, vendor/modules.txt
/kind bug
* Adds the certwatcher implementation from the internal pkg https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/webhook/internal/certwatcher/certwatcher.go
* Using github.com/kubernetes-sigs/controller-runtime/pkg/webhook directly is more involved at the moment and would require a breaking change (controller-runtime assumes the Cert/Key files are in the same directory, which external-snapshotter currently does not assume).
Fixes #422  
n/a
```release-note
The validation-webhook server will now watch for changes to …
```
=> Add certwatcher to webhook server

pkg/common-controller/framework_test.go, pkg/common-controller/snapshot_controller.go, pkg/common-controller/snapshot_create_test.go, pkg/common-controller/snapshotclass_test.go
>
/kind cleanup
In current implementation, SetDefaultSnapshotClass relies on PVC's StorageClass to find the driver name. Instead it's more appropriate to rely on PV's driver name as StorageClass can be updated after a volume has been provisioned.
This also removes the dependency on storage/v1
Fixes #404
```release-note
NONE
```
=> using csi driver from PV instead of from StorageClass

cmd/snapshot-controller/main.go, pkg/common-controller/framework_test.go, pkg/common-controller/snapshot_controller.go, pkg/common-controller/snapshot_controller_base.go, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go, pkg/utils/util.go
/kind feature
Adds snapshot controller metrics
Fixes #142 
Pending work:
~~1. Fix metric tests in pkg/metrics~~
~~2. emit metrics for non-success statuses~~
```release-note
The `--metrics-address` and `--metrics-path` flags have been added to support metrics for the snapshot-controller. To enable metrics, the user must configure a `--metrics-path` such as `:9102`. The default value for `--metrics-path` is the empty string, meaning this feature is disabled by default. The default value for `--metrics-path` is `/metrics`.
```
=> Add snapshot controller metrics

deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml, deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml, release-tools/build.make, release-tools/prow.sh
/kind cleanup
* Updates release tools to latest
* Squashed 'release-tools/' changes from 3041b8a..86ff580 
```
Squashed 'release-tools/' changes from 3041b8a..86ff580
86ff580 Merge pull request #116 from andyzhangx/export-image-name
c3a9662 allow export image name and registry name
c6a88c6 Merge pull request #113 from xing-yang/install_snapshot_controller
45ec4c6 Fix the install of snapshot CRDs and controller
5d874cc Merge pull request #112 from xing-yang/cleanup
79bbca7 Cleanup
d437673 Merge pull request #111 from xing-yang/update_snapshot_v1_rc
57718f8 Update snapshot CRD version
4aff857 Merge pull request #109 from pohly/alpha-test-defaults
0427289 Merge pull request #110 from pohly/kind-0.9-bazel-build-workaround …
```
=> Prow update release 3.0

cmd/snapshot-controller/main.go, pkg/common-controller/framework_test.go, pkg/common-controller/snapshot_controller.go, pkg/common-controller/snapshot_controller_base.go, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go, pkg/utils/util.go
/kind cleanup
Cherry-pick of 941821bf99ec8d30e7183d67decce4b5dd9bfee6 to release-3.0
n/a
n/a
```release-note
The `--http-endpoint` and `--metrics-path` flags have been added to support metrics for the snapshot-controller. To enable metrics, the user must configure a `--metrics-path` such as `:9102`. The default value for `--metrics-path` is the empty string, meaning this feature is disabled by default. The default value for `--metrics-path` is `/metrics`.
```
=> Cherry-pick:Add snapshot controller metrics

go.mod, pkg/validation-webhook/certwatcher.go, pkg/validation-webhook/webhook.go, pkg/validation-webhook/webhook_test.go, vendor/github.com/fsnotify/fsnotify/.editorconfig, vendor/github.com/fsnotify/fsnotify/.gitattributes, vendor/github.com/fsnotify/fsnotify/.gitignore, vendor/github.com/fsnotify/fsnotify/.travis.yml, vendor/github.com/fsnotify/fsnotify/AUTHORS, vendor/github.com/fsnotify/fsnotify/CHANGELOG.md, vendor/github.com/fsnotify/fsnotify/CONTRIBUTING.md, vendor/github.com/fsnotify/fsnotify/LICENSE, vendor/github.com/fsnotify/fsnotify/README.md, vendor/github.com/fsnotify/fsnotify/fen.go, vendor/github.com/fsnotify/fsnotify/fsnotify.go, vendor/github.com/fsnotify/fsnotify/go.mod, vendor/github.com/fsnotify/fsnotify/go.sum, vendor/github.com/fsnotify/fsnotify/inotify.go, vendor/github.com/fsnotify/fsnotify/inotify_poller.go, vendor/github.com/fsnotify/fsnotify/kqueue.go, vendor/github.com/fsnotify/fsnotify/open_mode_bsd.go, vendor/github.com/fsnotify/fsnotify/open_mode_darwin.go, vendor/github.com/fsnotify/fsnotify/windows.go, vendor/modules.txt
/kind bug
Cherry-pick of #429 
n/a
n/a
```release-note
The validation-webhook server will now watch for changes to --tls-cert-file and --tls-private-key-file and update the server's TLS config accordingly.
```
=> Cherry-pick: Add certwatcher to webhook server

cmd/snapshot-controller/main.go, pkg/common-controller/framework_test.go, pkg/common-controller/snapshot_controller.go, pkg/common-controller/snapshot_controller_base.go, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go, pkg/utils/util.go
Reverts kubernetes-csi/external-snapshotter#440
Metrics support is a new feature so we can't backport it.
=> Revert "Cherry-pick:Add snapshot controller metrics"

pkg/sidecar-controller/snapshot_controller.go, pkg/sidecar-controller/snapshot_delete_test.go
/kind bug
This is the release-3.0 cherrypick of https://github.com/kubernetes-csi/external-snapshotter/pull/423
Fixes #412
```release-note
NONE
```
=> [Cherry-pick] Don't check for snapshotClass when deleting content

.prow.sh, deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml, deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml, release-tools/build.make, release-tools/cloudbuild.yaml, release-tools/prow.sh
/kind cleanup
This forks release-tools for the release-2.1 branch. The current version of release-tools updates the snapshot CRD directory to what's in the 3.0 release, but also updates building to use this repo when testing snapshots it will actually test the snapshot version found here.
Hence we can use neither the head of release-tools, nor an old version. This means we need a fork of some sort, and so have to disable the release-tools subtree test.
```release-note
NONE
```
=> Update release-tools and prow script for release-2.1

pkg/common-controller/framework_test.go, pkg/common-controller/snapshot_controller_base.go, pkg/common-controller/snapshotclass_test.go
/kind bug
I've tested this manually on a cluster to confirm it fixes the crashlooping, as described in #445.
#445
```release-note
Backports fix #381 for crashloop when there are errors in the VolumeSnapshot, like a missing VolumeSnapshotClass.
```
=> Cherrypick #381 to 2.1.

CHANGELOG-2.1.md
Prepare 2.1.3 release. v2.1.3 tag can be created at this commit.
```release-note
NONE
```
=> Add change log for 2.1.3 release

deploy/kubernetes/snapshot-controller/rbac-snapshot-controller.yaml, deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
/kind feature
Provided manifests for external-snapshotter are not optimal in most use-cases.
Since external-snapshotter is most common component among various Kubernetes distributions and csi-plugins, I think we need to correct the manifests and include the following changes. They are needed to simplify the setup and provide optimal defaults for every user.
- Deploy external-snapshotter into kube-system namespace by default
- Enable leader-election
- Use Deployment instead of Statefulset and deploy minimum 2 replicas for redundancy
The following changes would allow to simple install working external-snapshotter using just few commands, as described here:
https://kubernetes-csi.github.io/docs/snapshot-controller.html#deplo …
=> Provide better defaults for external-snapshotter

.prow.sh, release-tools/prow.sh
As discussed in https://github.com/kubernetes/test-infra/pull/20792 we want to test on 1.20, but in this branch can only do it when using the v1beta1 API.
Related to https://github.com/kubernetes-csi/external-snapshotter/issues/472
This replaces https://github.com/kubernetes-csi/external-snapshotter/pull/471
```release-note
NONE
```
=> release-2.1: fix testing on Kubernetes 1.20

pkg/sidecar-controller/snapshot_controller.go
> /kind bug
The error returned from `CreateSnapshot` was overwritten by the call to `removeAnnVolumeSnapshotBeingCreated`, making the corresponding event look like this:
```
default     5m42s       Warning   SnapshotCreationFailed   volumesnapshotcontent                   Failed to create snapshot: failed to take snapshot of the volume, 6e34868e-6982-11eb-9971-0a58ac14d08c: %!q(<nil>)
```
(Note the `%!q(<nil>)` part in the end.)
Retain the error through variable shadowing so that it can be propagated and reported upwards the call stack.
We also improve the error line by dropping an unnecessary comma and dequoting the error string (since we already employ a colon separator).
**Does this PR introduce a user-facing …
=> Retain CreateSnapshot error

pkg/common-controller/snapshot_controller.go, pkg/utils/util.go, pkg/validation-webhook/snapshot.go, pkg/validation-webhook/validation.go
Signed-off-by: prateekpandey14 <prateekpandey14@gmail.com>
/kind cleanup
Refactor and move snapshot specific validations to `pkg/validation-webhook` folder
Fixes #443 
```release-note
NONE
```
=> Move snapshot validations to validation-webhook directory

cmd/csi-snapshotter/main.go
/kind bug
We do not honor httpEndpoint when it's provided. 
Fixes #492
n/a
```release-note
--http-endpoint will now correctly be used for the metrics server address when --metrics-address is not provided.
```
=> Fix snapshotter metrics server to use http-endpoint when provided

cmd/csi-snapshotter/main.go
/kind cleanup
Cherry-pick of #496 
n/a
n/a
```release-note
--http-endpoint will now correctly be used for the metrics server address when --metrics-address is not provided.
```
=> Fix snapshotter metrics server to use httpEndpoint when provided

pkg/sidecar-controller/snapshot_controller.go
/kind bug
Currently if we fail to create a snapshot in a CSIFinalError way, the error is overwritten when we attempt to remove the annotation on the content. This can result in the snapshot controller logging the error, but subsequent logs (and events) being nil:
> I0420 18:59:30.106430       1 snapshot_controller.go:301] createSnapshotWrapper: CreateSnapshot for content snapcontent-5e494f19-ea35-480c-89f8-626e6ad1dbd3 returned error: rpc error: code = Unknown desc = AzureDisk - invalid option invalid in VolumeSnapshotClass
> ...
> E0420 18:59:30.506775       1 snapshot_controller.go:105] createSnapshot for content [snapcontent-5e494f19-ea35-480c-89f8-626e6ad1dbd3]: error occurred in createSnapshotWrapper: failed to take …
=> Correct snapshotContent error propagation

client/config/crd/snapshot.storage.k8s.io_volumesnapshotclasses.yaml, client/config/crd/snapshot.storage.k8s.io_volumesnapshotcontents.yaml, client/config/crd/snapshot.storage.k8s.io_volumesnapshots.yaml
Change storage version from v1beta1 to v1 and add deprecation warnings.
Fixes #
```release-note
Changes VolumeSnapshot API storage version from v1beta1 to v1; VolumeSnapshot v1beta1 is deprecated and will be removed in a future release.
```
=> Change storage version from v1beta1 to v1

cmd/snapshot-controller/main.go
/kind bug
In the upgrade to the v1 version of VolumeSnapshots from v1beta with a deployment rollout of the controller it might be possible to get into a state where the v1 snapshot-controller is up but the CRDs for v1 aren't applied yet (from https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/)
> It might take a few seconds for the endpoint to be created. You can watch the Established condition of your CustomResourceDefinition to be true or watch the discovery information of the API server for your resource to show up.
To test it I had 2 replicas of the v3 controller in a cluster and I did `kubectl apply -f` with the following:
```
apiVersion: apps/v1
kind: Deployment …
```
=> Make sure the v1 CRDs exist before starting the controller

README.md, cmd/csi-snapshotter/main.go, cmd/snapshot-controller/main.go, go.mod, go.sum, pkg/common-controller/framework_test.go, pkg/common-controller/snapshot_controller.go, pkg/common-controller/snapshot_controller_base.go, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go, pkg/utils/util.go, pkg/validation-webhook/certwatcher.go, vendor/github.com/kubernetes-csi/csi-lib-utils/connection/connection.go, vendor/github.com/kubernetes-csi/csi-lib-utils/leaderelection/leader_election.go, vendor/github.com/kubernetes-csi/csi-lib-utils/metrics/metrics.go, vendor/github.com/kubernetes-csi/csi-lib-utils/rpc/common.go, vendor/modules.txt
This PR contains cherry-picks of #409 and #439, which each provide an `--http-endpoint` flag for the snapshot-controller and csi-snapshotter.
This is already present in v4; backporting so v3 users can make use of leader election health checks and have a consistent `--http-endpoint` flag across the snapshot-controller and csi-snapshotter.
```release-note
The `--http-endpoint` and `--metrics-path` flags have been added to support metrics for the snapshot-controller. To enable metrics, the user must configure a `--metrics-path` such as `:9102`. The default value for `--metrics-path` is the empty string, meaning this feature is disabled by default. The default …
```
=> Cherry-picks of #409 and #439: Adding --http-endpoint to snapshot components

release-tools/SIDECAR_RELEASE_PROCESS.md, release-tools/go-get-kubernetes.sh, release-tools/prow.sh, release-tools/pull-test.sh
Squashed 'release-tools/' changes from a1e11275..6616a6b5
[6616a6b5](https://github.com/kubernetes-csi/csi-release-tools/commit/6616a6b5) Merge [pull request #146](https://github.com/kubernetes-csi/csi-release-tools/pull/146) from pohly/kubernetes-1.21
[510fb0f9](https://github.com/kubernetes-csi/csi-release-tools/commit/510fb0f9) prow.sh: support Kubernetes 1.21
[c63c61b3](https://github.com/kubernetes-csi/csi-release-tools/commit/c63c61b3) prow.sh: add CSI_PROW_DEPLOYMENT_SUFFIX
[51ac11c3](https://github.com/kubernetes-csi/csi-release-tools/commit/51ac11c3) Merge [pull request #144](https://github.com/kubernetes-csi/csi-release-tools/pull/144) from pohly/pull-jobs
[dd54c926](https://github.com/kubernetes-csi/csi-release-tools/commit/dd54c926) pull-test.sh: test importing …
=> release-4.1: update release-tools

README.md
At present the snapshot readme guide point out the snapshot beta CRD installation. However as we have moved to GA version of snapshot CRD, we dont need the references in the readme file to Beta CRD. This PR address the same.
```release-note-none
```
=> correct snapshot controller installation doc 

README.md, cmd/csi-snapshotter/main.go, pkg/sidecar-controller/framework_test.go, pkg/sidecar-controller/snapshot_controller_base.go
Two new timeout values ( retryIntervalStart & retryIntervalMax )
have been added to set the ratelimiter for volumesnapshotcontent queue.
Fixes:  https://github.com/kubernetes-csi/external-snapshotter/issues/463
```release-note
`retry-interval-start` and `retry-interval-max` arguments are added to csi-snapshotter sidecar which controls retry interval of failed volume snapshot creation and deletion. These values set the ratelimiter for volumesnapshotcontent queue.
```
=> Add ability to customize VolumeSnapshotContent workqueue

README.md, cmd/csi-snapshotter/main.go, cmd/snapshot-controller/main.go, pkg/common-controller/framework_test.go, pkg/common-controller/snapshot_controller_base.go
This patch adds two new parameters `retryIntervalStart & retryIntervalMax`
which can be configured to adjust the ratelimiters of snapshotqueue and contentqueue
in the controller.
```release-note
`retry-interval-start` and `retry-interval-max` arguments are added to common-controller
which controls retry interval of failed volume snapshot creation and deletion.
These values set the ratelimiter for snapshot and content queues.
```
=> Allow tuning common-controller Ratelimiter with `retryIntervalStart & retryIntervalMax`

pkg/common-controller/snapshot_controller.go, pkg/sidecar-controller/snapshot_controller.go
/kind bug
When removeAnnVolumeSnapshotBeingCreated fails, updatedContent is not returned.
Part of #525 
This does not completely fix the problem, but it does seem to lower the count.
```release-note
NONE
```
=> Return VolumeSnapshotContent from various functions instead of nil

client/config/crd/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
/kind feature
When using `kubectl get volumesnapshotcontent` the result prints also referenced VolumeSnapshot object. That is not enough to identify the correct one though, since VolumeSnapshot is namespaced. It would be probably good to display also the namespace of the VolumeSnapshot.
Yes.
```release-note
The namespace of the referenced VolumeSnapshot is printed when printing a VolumeSnapshotContent.
```
=> Add VS namespace to VSC printed columns

README.md, cmd/csi-snapshotter/main.go
/kind feature
Similar to kubernetes-csi/external-provisioner#643, this change adds command line arguments to configure leader election parameters.
Fixes #
```release-note
Add command line arguments to configure leader election options
```
=> Add command line arguments to configure leader election options

pkg/common-controller/snapshot_controller.go
Fixes: #522
>
> /kind bug
> /kind design
/kind feature
> /kind flake
Adds `SnapshotCreated` and `SnapshotReady` events to snapshot-controller.
Fixes #522 
**Special notes for your reviewer**: This is my first PR here, and I hope this is the expected change, but if not, please let me know and I'll look into it right away. Thanks!
```release-note
Introduced "SnapshotCreated" and "SnapshotReady" events.
```
=> Add "SnapshotCreated" event for snapshot-controller

cmd/snapshot-validation-webhook/Dockerfile
/kind cleanup
The webhook image needlessly used the distroless image containing glibc. The webhook server is a static binary, so it can be packaged using the distroless/static image like the other components.
This should make image security scanners happy. As minor benefits, it also slightly decreases image size and makes it so that the same base image is used for all components
```release-note
NONE
```
=> Use distroless/static image for webhook

pkg/sidecar-controller/snapshot_controller.go
Cherry pick of #470 on release-3.0.
#470: Retain CreateSnapshot error
For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.
```release-note
Cherry-pick #470: Retain CreateSnapshot Error
```
=> [release-3.0] Automated cherry pick of #470: Retain CreateSnapshot error

pkg/common-controller/snapshot_controller.go
/kind cleanup
This PR removes checks that are performed as part of the webhook after https://github.com/kubernetes-csi/external-snapshotter/issues/187 was closed. 
Fixes #
```release-note
Remove redundant validation checks.
```
=> Remove redundant validation checks

go.mod, vendor/modules.txt
The snapclient reference from the external-snapshotter package `4.0.0` which has been lifted to `4.1.1` tag
The snapshot client was depending on kube 1.19.0 before and it has been updated to 1.21.0
-->
```release-note-none
```
=> snap client version update and kube dependency update

pkg/sidecar-controller/snapshot_controller.go
Cherry pick of #470 on release-4.0.
#470: Retain CreateSnapshot error
For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.
```release-note
Cherry-pick #470: Retain CreateSnapshot Error
```
=> [release-4.0] Automated cherry pick of #470: Retain CreateSnapshot error

pkg/metrics/metrics.go, pkg/metrics/metrics_test.go
>
/kind bug
> /kind design
> /kind flake
process_start_time metric needs to be initialized for cummulative latency metric.
Fixes #
The component-base [v0.22.0-rc.0](https://github.com/kubernetes-csi/external-snapshotter/blob/master/go.mod#L41)
contains the [bug-fix](https://github.com/kubernetes/component-base/commit/791c326f981f31f14efdfd177a9a869f01038f1a) for [RegisterProcessStartTime](https://github.com/kubernetes-csi/external-snapshot …
=> Add process_start_time_seconds metric

README.md, cmd/snapshot-controller/main.go
/kind feature
This PR adds CLI arguments to configure leader election options in the snapshot-controller.
This was missed in PR #538.
Fixes #
```release-note
Add command line arguments to configure leader election options for the snapshot controller.
```
=> Add options to configure leader election in snapshot-controller

cmd/snapshot-controller/main.go, pkg/common-controller/framework_test.go, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go, pkg/sidecar-controller/snapshot_controller_base.go
/kind bug
- Needed to start the http server outside of pkg/metric for the snapshot controller
- We needed this because we want to add other endpoints to the server
Fixes #572 
```release-note
Adds the leader election health check for the snapshot controller at `/healthz/leader-election`
```
=> Refactor http server and register leaderelection health check

pkg/metrics/metrics.go
/kind bug
/kind flake
`RecordMetrics()` grabs a mutex and calls `recordCancelMetric()`, which wants to grab the same mutex. Go mutexes are not recursive, so `recordCancelMetric` blocks forever.
`recordCancelMetric` should not grab the mutex, all its callers already have the mutex.
Fixes #580
```release-note
Fixed deadlock in reporting metrics.
```
=> Fix deadlock in recursive metric locks

deploy/kubernetes/csi-snapshotter/rbac-csi-snapshotter.yaml, deploy/kubernetes/snapshot-controller/rbac-snapshot-controller.yaml, go.mod, pkg/common-controller/framework_test.go, pkg/common-controller/snapshot_controller.go, pkg/common-controller/snapshot_finalizer_test.go, pkg/common-controller/snapshot_update_test.go, pkg/sidecar-controller/content_create_test.go, pkg/sidecar-controller/framework_test.go, pkg/sidecar-controller/snapshot_controller.go, pkg/utils/patch.go, vendor/modules.txt
/kind bug
This PR addresses the "object has been modified" issue we see a lot in the snapshot-controller/snapshotter.
Before this PR, we were seeing ~30-50 occurrences of this error in the snapshot-controller/snapshotter logs.
This PR only addresses the problematic areas found in the e2e PR tests. If we continue to see more of these errors, we can    address replace the remaining Update/UpdateStatus calls in a separate PR.
Fixes #525 
n/a
```release-note
Replaces many VolumeSnapshot/VolumeSnapshotContent Update/UpdateStatus operations with …
```
=> Use JSON patch for many VolumeSnapshot and VolumeSnapshotContent updates

pkg/sidecar-controller/snapshot_controller.go
/kind bug
Patches the entire status object when status is nil
n/a
n/a
```release-note
NONE
```
=> Fix an issue where patch will fail when status is nil

client/apis/volumesnapshot/v1/types.go, client/apis/volumesnapshot/v1beta1/types.go, client/config/crd/snapshot.storage.k8s.io_volumesnapshotclasses.yaml, client/config/crd/snapshot.storage.k8s.io_volumesnapshotcontents.yaml, client/config/crd/snapshot.storage.k8s.io_volumesnapshots.yaml, vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/apis/volumesnapshot/v1/types.go, vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/apis/volumesnapshot/v1beta1/types.go
/kind feature
This allows end users to run `kubectl get vs`, for example, instead of
`kubectl get volumesnapshot`. The following short names have been
implemented:
* `VolumeSnapshot` - `vs`
* `VolumeSnapshotContent` - `vsc`, `vscs`
* `VolumeSnapshotClass` - `vsclass`, `vsclasses`
Fixes #603
Yes
```release-note
Added short names for Volume Snapshot CRDs:
* VolumeSnapshot - vs
* VolumeSnapshotContent - vsc, vscs
* VolumeSnapshotClass` - vsclass, vsclasses
```
=> Add short names for Volume Snapshot CRDs

deploy/kubernetes/webhook-example/create-cert.sh
=> Update CertificateSigningRequest apiversion to V1

README.md, client/config/crd/kustomization.yaml, deploy/kubernetes/csi-snapshotter/kustomization.yaml, deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml, deploy/kubernetes/snapshot-controller/kustomization.yaml
>
> /kind bug
> /kind design
> /kind flake
/kind design
The changes introduced with this PR allow for better integration of the controller components and, in particular, the CRDs (which other projects rely on) into a GitOps workflow by providing a means to reference versioned manifests via `kustomize`.
Fixes #605 
none
```release-note
Added kustomization manifests to CRDs and controller …
```
=> Add kustomization manifests to CRDs and controller components

README.md, cmd/csi-snapshotter/main.go, cmd/snapshot-controller/main.go, go.mod, vendor/modules.txt
>
> /kind bug
> /kind design
/kind feature
>/kind flake
This change adds two new flags "kube-api-qps" and "kube-api-burst" to make the QPS and Burst of clients to the API server configurable. Their default values stay the same as defaults of kube client.
**Experiment**
To justify the necessity to make this change, we run experiments on external-snapshotters between defaullt qps and burst and a pair of hardcoded ones. Following are the results for 32 threads runs.
1) Default QPS and Burst: QPS=5.0 and Burst=10
| …
=> Make the QPS and Burst of kube client config to be configurable

README.md, cmd/csi-snapshotter/main.go, cmd/snapshot-controller/main.go, go.mod, vendor/modules.txt
>
> /kind bug
> /kind design
/kind feature
> /kind flake
I was asked to backport the changes merged in #621 to the release-5.0 branch: https://github.com/kubernetes-csi/external-snapshotter/pull/621#issuecomment-988320585
Fixes #
N/A
```release-note
Cherry-pick #621: Make the QPS and Burst of kube client config to be configurable in both snapshot-controller and CSI snapshotter sidecar
```
=> Backport #621 to release-5.0

cmd/csi-snapshotter/main.go, cmd/snapshot-controller/main.go, go.mod, vendor/modules.txt
>
/kind bug
> /kind design
> /kind flake
There is an issue introduced by #621 that the pflag were not added to the go flag set, so that the pflag cmd option, `kube-api-qps`, was not exposed. This PR fixes this bug by getting rid of the dependency on pflag package.
Fixes #
N/A
**Testing**
```
$./bin/csi-snapshotter -h
...
--kube-api-burst int                        Burst to use while communicating with the kubernetes apiserver. Defaults to 10. (default 10)
--kube-api-qps …
```
=> Fixed the bug introduced by PR 621 and exposed the kube-api-qps cmd option properly

cmd/csi-snapshotter/main.go, cmd/snapshot-controller/main.go, go.mod, vendor/modules.txt
>
/kind bug
> /kind design
> /kind flake
Backport the changes merged in #626 to the release-5.0
Fixes #
```release-note
Cherry-pick #626: Fixed a bug introduced by PR 621 and exposed the kube-api-qps cmd option properly
```
=> Backport #626 to release-5.0

README.md, cmd/csi-snapshotter/main.go, cmd/snapshot-controller/main.go, deploy/kubernetes/snapshot-controller/rbac-snapshot-controller.yaml, go.mod, go.sum, pkg/common-controller/framework_test.go, pkg/common-controller/snapshot_controller.go, pkg/common-controller/snapshot_controller_base.go, pkg/common-controller/snapshot_controller_test.go, pkg/utils/util.go, vendor/k8s.io/component-helpers/LICENSE, vendor/k8s.io/component-helpers/scheduling/corev1/doc.go, vendor/k8s.io/component-helpers/scheduling/corev1/helpers.go, vendor/k8s.io/component-helpers/scheduling/corev1/nodeaffinity/nodeaffinity.go, vendor/modules.txt
>
> /kind bug
> /kind design
/kind feature
> /kind flake
This PR will allow snapshot sidecar controller to be deployed on every node along with the CSI drivers that handle local volumes:
1. Added a parameter "--node-deployment", which should be set to true when the sidecar is being deployed on a per node basis.
2. For these changes to work, NODE_NAME environment variable must also be set while deploying the sidecar controller.
3. With these changes, the common snapshot controller checks the node affinity for the PV related …
=> Implement distributed snapshotting

release-tools/cloudbuild.yaml, release-tools/prow.sh
/kind cleanup
Update release tools and pull in the change to increase the timeout value to allow all snapshot images to be build before the timeout.
Fixes #
Squashed 'release-tools/' changes from a6a1a797..4aedf357
4aedf357 Merge pull request #178 from xing-yang/timeout
2b9897eb Increase build timeout
51d37029 Merge pull request #177 from mauriciopoppe/kind-image-1.23
a30efeac Add kind image for 1.23
git-subtree-split: 4aedf357cac90c044cf3c2b8ff189520e3fd37b2
```release-note
NONE
```
=> release-5.0: Update release tools 5.0

release-tools/cloudbuild.yaml, release-tools/prow.sh
/kind cleanup
Update release tools and pull in the change to increase the timeout value to allow all snapshot images to be build before the timeout.
Fixes #637 
Squashed 'release-tools/' changes from a6a1a797..4aedf357
4aedf357 Merge pull request #178 from xing-yang/timeout
2b9897eb Increase build timeout
51d37029 Merge pull request #177 from mauriciopoppe/kind-image-1.23
a30efeac Add kind image for 1.23
git-subtree-split: 4aedf357cac90c044cf3c2b8ff189520e3fd37b2
```release-note
NONE
```
=> Update release tools 5.0

deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml, deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml, deploy/kubernetes/webhook-example/webhook.yaml
>
/kind bug
> /kind design
> /kind flake
This PR fixes issue 630. It changes the snapshot controller image version in the setup script to v4.2.1.
Fixes #630 
```release-note
NONE
```
=> Change snapshot controller image version to 4.2.1

cmd/snapshot-validation-webhook/Dockerfile
Cherry pick of #550 on release-4.0.
#550: Use distroless/static image for webhook
For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.
```
Cherry-pick #550: Use distroless/static image for webhook
```
=> [release-4.0] Automated cherry pick of #550: Use distroless/static image for webhook

release-tools/KUBERNETES_CSI_OWNERS_ALIASES, release-tools/SIDECAR_RELEASE_PROCESS.md, release-tools/build.make, release-tools/cloudbuild.yaml, release-tools/prow.sh
Squashed 'release-tools/' changes from a6a1a797..335339f0
[335339f0](https://github.com/kubernetes-csi/csi-release-tools/commit/335339f0) Merge [pull request #187](https://github.com/kubernetes-csi/csi-release-tools/pull/187) from mauriciopoppe/remove-eol-windows-versions
[890b87a2](https://github.com/kubernetes-csi/csi-release-tools/commit/890b87a2) Merge [pull request #188](https://github.com/kubernetes-csi/csi-release-tools/pull/188) from pwschuurman/update-release-notes-docs
[274bc9ba](https://github.com/kubernetes-csi/csi-release-tools/commit/274bc9ba) Update Sidecar Release Process documentation to reference latest syntax for release-notes tool
[87b6c372](https://github.com/kubernetes-csi/csi-release-tools/commit/87b6c372) Merge [pull request …
=> release-4.2: update release-tools

pkg/sidecar-controller/snapshot_controller_base.go
>
/kind bug
> /kind design
> /kind flake
Fixes #
Backport #651, #666 and #669
```release-note
Backport #651, #666 and #669: Avoid constantly retries CreateSnapshot call on error without exponential backoff
```
=> Backport: Avoid constantly retries CreateSnapshot call on error without exponential backoff

client/apis/volumesnapshot/v1/types.go, client/apis/volumesnapshot/v1/zz_generated.deepcopy.go, vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/apis/volumesnapshot/v1/types.go, vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/apis/volumesnapshot/v1/zz_generated.deepcopy.go
This PR updates the type of `SourceVolumeMode` from `string` to `v1.PersistentVolumeMode`. Also update the generated code and vendored dependancies. 
Fixes #
```release-note
Change SourceVolumeMode type to v1.PersistentVolumeMode
```
=> Change SourceVolumeMode type to v1.PersistentVolumeMode

client/apis/volumesnapshot/v1/types.go, client/apis/volumesnapshot/v1/zz_generated.deepcopy.go, vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/apis/volumesnapshot/v1/types.go, vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/apis/volumesnapshot/v1/zz_generated.deepcopy.go
Cherry pick of https://github.com/kubernetes-csi/external-snapshotter/pull/683
Fixes #
```release-note
Cherry-pick #683: Change SourceVolumeMode type to v1.PersistentVolumeMode
```
=> [Cherry-pick] Change SourceVolumeMode type to v1.PersistentVolumeMode.

cmd/snapshot-controller/main.go, pkg/common-controller/framework_test.go, pkg/common-controller/snapshot_controller.go, pkg/common-controller/snapshot_controller_base.go
/kind feature
This PR adds changes to snapshot-controller to read the volume mode of the source PV and add it to the `Spec.SourceVolumeMode` field of the to-be-created `VolumeSnapshotContent` object. 
Also introduce a feature flag for this feature. 
KEP - https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/3141-prevent-volume-mode-conversion
Testing
1. Deploy Hostpath CSI driver with `v6.0.0-rc2` version of `csi-snapshotter` and `VolumeSnapshotContent` CRD. Set `prevent-volume-mode-conversion` to `true` in `snapshot-controller`. 
```
% kubectl get deployment -n kube-system -o yaml snapshot-controller
apiVersion: apps/v1
kind: Deployment
...
spec:
minReadySeconds: 15
progressDeadlineSeconds: 600
... …
```
=> Changes to snapshot controller to add sourceVolumeMode

release-tools/prow.sh, release-tools/verify-spelling.sh
Squashed 'release-tools/' changes from 335339f0..37d11049
[37d11049](https://github.com/kubernetes-csi/csi-release-tools/commit/37d11049) Merge [pull request #191](https://github.com/kubernetes-csi/csi-release-tools/pull/191) from pohly/go-1.18
[db917f5c](https://github.com/kubernetes-csi/csi-release-tools/commit/db917f5c) update to Go 1.18
git-subtree-split: 37d1104926b30aa0544abb5a16c980ba82aaa585
```release-note
NONE
```
=> release-6.0: update release-tools

release-tools/prow.sh, release-tools/verify-spelling.sh
Squashed 'release-tools/' changes from 335339f0..37d11049
[37d11049](https://github.com/kubernetes-csi/csi-release-tools/commit/37d11049) Merge [pull request #191](https://github.com/kubernetes-csi/csi-release-tools/pull/191) from pohly/go-1.18
[db917f5c](https://github.com/kubernetes-csi/csi-release-tools/commit/db917f5c) update to Go 1.18
git-subtree-split: 37d1104926b30aa0544abb5a16c980ba82aaa585
```release-note
NONE
```
=> release-5.0: update release-tools

cmd/snapshot-controller/main.go, pkg/common-controller/framework_test.go, pkg/common-controller/snapshot_controller.go, pkg/common-controller/snapshot_controller_base.go
/kind feature
Cherry pick of https://github.com/kubernetes-csi/external-snapshotter/pull/679
Fixes #
```release-note
Cherry-pick #679: Changes to snapshot controller to add SourceVolumeMode to VolumeSnapshotContents
```
=> [Cherry-pick] Changes to snapshot controller to add SourceVolumeMode to VolumeSnapshotContents

pkg/validation-webhook/scheme.go, pkg/validation-webhook/snapshot.go, pkg/validation-webhook/snapshot_test.go, pkg/validation-webhook/webhook.go, pkg/validation-webhook/webhook_test.go
>
/kind bug
> /kind design
> /kind flake
Adding validation so that a user can not create or update to a situation where they have more than default VolumeSnapshotClass
backport of #674 
```release-note
Cherry-pick #674: snapshot-validation-webhook: Adding validation for VolumeSnapshotClass to only have a single default for a particular driver. 
```
=> Backport 674: Adding validation for default snapshot classes per driver

deploy/kubernetes/csi-snapshotter/rbac-csi-snapshotter.yaml
Removed Create and Delete verb for volumesnapshotcontents
Resource in the external-snapshotter-runner clusterRole.
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Fixes #
```release-note
Remove create and delete access of volumesnapshotcontents resource from csi-snapshotter RBAC as it's no longer required.
```
=> Remove create and delete from csi-snapshotter RBAC

README.md, deploy/kubernetes/webhook-example/admission-configuration-template
Updating the readme based on the new kubeconfig flag for the webhook and webhook template such that the webhook will be used for volumesnapshotclasses as well
```release-note
NONE
```
=> Updating readme and webhook tempate to capture changes made for volumesnapshotclasses

deploy/kubernetes/csi-snapshotter/rbac-csi-snapshotter.yaml
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
cherry-pick of #689: Removed Create and Delete verb for volumesnapshotcontents Resource in the external-snapshotter-runner clusterRole.
(cherry picked from commit 7748d5ffb6f8f748153af224f85e2f86283d66ab)
Fixes #
```release-note
cherry-pick of #689: Remove create and delete access of volumesnapshotcontents resource from csi-snapshotter RBAC as it's …
```
=> Backport: Remove create and delete from csi-snapshotter RBAC

client/apis/volumesnapshot/v1/types.go
/kind cleanup
This PR is a follow-up feedback from @xing-yang at https://github.com/kubernetes-csi/docs/pull/506#discussion_r850992275 to remove a stale TODO item, so that the new CRD API documentation inherits the latest info from the types.go file.
Part of #102.
```release-note
NONE
```
=> Update comment in types.go for the new CRD docs

client/apis/volumesnapshot/v1/types.go
/kind cleanup
This PR backports commit d470451a2f9eef2ac17315302dd6579d237a17c0 to release-6.0, as requested by @xing-yang. See https://github.com/kubernetes-csi/external-snapshotter/pull/697#issuecomment-1101002492.
Part of https://github.com/kubernetes-csi/external-snapshotter/issues/102.
```release-note
NONE
```
=> Backport: Update comment in types.go, to be included in the new CRD docs

pkg/validation-webhook/snapshot.go, pkg/validation-webhook/webhook.go, vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/apis/volumesnapshot/v1/types.go
/kind feature
This PR adds changes to snapshot-validation-webhook to make the `SourceVolumeMode` field immutable. 
KEP - https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/3141-prevent-volume-mode-conversion
Testing 
1. Deploy `snapshot-controller` with https://github.com/kubernetes-csi/external-snapshotter/pull/679
2. Create `VolumeSnapshot` object and attempt to alter `Spec.SourceVolumeMode` from `Filesystem` to `Block`. The attempt fails with the below error:
```
% kubectl edit volumesnapshotcontent                  
error: volumesnapshotcontents.snapshot.storage.k8s.io "snapcontent-bbf7be38-ccb9-46bf-a420-f1a436bf10e4" could not be patched: admission webhook …
```
=> Add webhook to make SourceVolumeMode immutable

pkg/validation-webhook/snapshot.go, pkg/validation-webhook/webhook.go, vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/apis/volumesnapshot/v1/types.go
Backport of https://github.com/kubernetes-csi/external-snapshotter/pull/680
/kind feature
Fixes #
```release-note
Cherry-pick #680: Add webhook to make SourceVolumeMode immutable
```
=> Backport: Add webhook to make SourceVolumeMode immutable

cmd/snapshot-controller/main.go, deploy/kubernetes/csi-snapshotter/rbac-external-provisioner.yaml, deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml, deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml, pkg/common-controller/framework_test.go, pkg/common-controller/snapshot_controller.go, pkg/common-controller/snapshot_controller_test.go, pkg/common-controller/snapshot_create_test.go, pkg/common-controller/snapshot_delete_test.go, pkg/common-controller/snapshot_finalizer_test.go, pkg/sidecar-controller/content_create_test.go, pkg/sidecar-controller/csi_handler.go, pkg/sidecar-controller/framework_test.go, pkg/sidecar-controller/snapshot_controller.go, pkg/sidecar-controller/snapshot_delete_test.go, pkg/utils/util.go, pkg/validation-webhook/scheme.go, pkg/validation-webhook/webhook.go, pkg/validation-webhook/webhook_test.go
This PR address the below:
/kind cleanup
-->
```release-note
NONE
```
=> replace serviceAccountName key, rbac and cleanup in the code

README.md, deploy/kubernetes/webhook-example/admission-configuration-template
Updating the readme based on the new kubeconfig flag for the webhook and webhook template such that the webhook will be used for volumesnapshotclasses as well
```release-note
Cherry-pick #688: Action required: Added admission webhook to ensure that only one VolumeSnapshotClass can be default for each CSI driver. To benefit from this validation, please update your webhook configuration as shown in deploy/kubernetes/webhook-example/admission-configuration-template.```
=> Backport 688: Updating readme and webhook tempate to capture changes made for volumesnapshotclasses 

deploy/kubernetes/webhook-example/README.md, deploy/kubernetes/webhook-example/rbac-snapshot-webhook.yaml, deploy/kubernetes/webhook-example/webhook.yaml
/kind bug
Adds RBAC to the validating webhook example so that it can be deployed.
When installing the webhook through the example, currently the webhook will crash loop while not being able to get access to the volumesnapshotclass list/watch. With this change the example will get access.
Fixes #705 
```release-note
Adding RBAC file to webhook example for updated validating webhook
```
=> Adding webhook RBAC to enable validation of snapshotclasses

deploy/kubernetes/webhook-example/README.md, deploy/kubernetes/webhook-example/rbac-snapshot-webhook.yaml, deploy/kubernetes/webhook-example/webhook.yaml
/kind bug
Adds RBAC to the validating webhook example so that it can be deployed.
When installing the webhook through the example, currently the webhook will crash loop while not being able to get access to the volumesnapshotclass list/watch. With this change the example will get access.
Fixes #705 
```release-note
Adding RBAC file to webhook example for updated validating webhook
```
=> Backport-706 Adding webhook RBAC to enable validation of snapshotclasses

cmd/snapshot-controller/main.go, deploy/kubernetes/csi-snapshotter/rbac-external-provisioner.yaml, deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml, deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml, pkg/common-controller/framework_test.go, pkg/common-controller/snapshot_controller.go, pkg/common-controller/snapshot_controller_test.go, pkg/common-controller/snapshot_create_test.go, pkg/common-controller/snapshot_delete_test.go, pkg/common-controller/snapshot_finalizer_test.go, pkg/sidecar-controller/content_create_test.go, pkg/sidecar-controller/csi_handler.go, pkg/sidecar-controller/framework_test.go, pkg/sidecar-controller/snapshot_controller.go, pkg/sidecar-controller/snapshot_delete_test.go, pkg/utils/util.go, pkg/validation-webhook/scheme.go, pkg/validation-webhook/webhook.go, pkg/validation-webhook/webhook_test.go
/kind cleanup
Backport #690 to release-6.0.
Fixes #
```release-note
NONE
```
=> Backport 690: replace serviceAccountName key, rbac and cleanup in the code

client/config/crd/snapshot.storage.k8s.io_volumesnapshotclasses.yaml, client/config/crd/snapshot.storage.k8s.io_volumesnapshotcontents.yaml, client/config/crd/snapshot.storage.k8s.io_volumesnapshots.yaml, client/hack/README.md
This PR adds back the `v1beta1` manifests. Generated files are not added back as part of this PR. 
Fixes #
```release-note
Add v1beta1 manifests back to external-snapshotter 
```
=> Add back v1beta1 manifests

client/config/crd/snapshot.storage.k8s.io_volumesnapshotclasses.yaml, client/config/crd/snapshot.storage.k8s.io_volumesnapshotcontents.yaml, client/config/crd/snapshot.storage.k8s.io_volumesnapshots.yaml, client/hack/README.md
(cherry picked from commit 5c47a8ceb4d950c42729eee43e4f74a5b3ab8e6a)
Cherry-pick #718 
Fixes #
```release-note
Cherry-pick #718: Add VolumeSnapshot v1beta1 manifests back. VolumeSnapshot v1beta1 APIs are no longer served.
Action Item: Please update to VolumeSnapshot v1 APIs as soon as possible.
```
=> Backport 718: Add back v1beta1 manifests

deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml, deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml, deploy/kubernetes/webhook-example/webhook.yaml
/kind bug
Since 4f783f10f added validation for `volumesnapshotclasses`, the
`snapshot-validation-webhook` needs to handle this kind of resource. But
version 5.0.1 doesn't, which leads to failures when updating or creating
`volumesnapshotclasses`.
This commit updates the `snapshot-validation-webhook` version to 6.0.1 in
`deploy/kubernetes/webhook-example/admission-configuration-template`.
This is a fairly trivial change, in a directory labeled as an example, so I don't think it warrants a release note.
=> deploy/kubernetes: Update snapshot-validation-webhook

deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml, deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml, deploy/kubernetes/webhook-example/webhook.yaml
What type of PR is this?
/kind feature deprecation
What this PR does / why we need it:
Related to:
https://github.com/kubernetes-csi/external-snapshotter/pull/687
Switch to the new endpoint for container images. See: https://github.com/kubernetes/k8s.io/wiki/New-Registry-url-for-Kubernetes-(registry.k8s.io)
Special notes for your reviewer:
registry.k8s.io is currently a redirect to k8s.gcr.io. The change should be transparent to any pulling from k8s.gcr.io.
Does this PR introduce a user-facing change?:
NONE
=> use registry.k8s.io for deployment

pkg/common-controller/framework_test.go, pkg/common-controller/snapshot_controller.go, pkg/common-controller/snapshot_update_test.go, pkg/common-controller/snapshotclass_test.go, pkg/sidecar-controller/framework_test.go, pkg/sidecar-controller/snapshot_controller.go, pkg/utils/util.go
```release-note
NONE
```
Additional Note for reviewer:
The errors in absence of this PR cause tests to fail in https://github.com/kubernetes-csi/csi-release-tools/pull/203
=> make the formatting errors based on go 1.19

client/apis/volumesnapshot/v1/types.go, client/clientset/versioned/fake/register.go, client/clientset/versioned/scheme/register.go, pkg/common-controller/snapshot_controller.go
```release-note
NONE
```
Additional Note for reviewer:
Eventhough we tried to minimize the changes for the unit test to pass with go 1.19 here https://github.com/kubernetes-csi/external-snapshotter/pull/758, it is not enough . 
The test is failing here https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-csi_csi-release-tools/203/pull-kubernetes-csi-release-tools-external-snapshotter/1569716664243589120 . This PR holds the required changes, however this has changes in client package too. Also the formatting we discussed here https://github.com/kubernetes-csi/external-snapshotter/pull/758#discussion_r964520500 getting adjusted to different representation by the gofmt tool as in this PR.
=> update client package with go 1.19 formatting changes

README.md, cmd/snapshot-controller/main.go
Add a command line flag (retry-crd-interval-max) for the maximum interval to wait for CRDs to appear.
This allows providers to avoid unnecessary crashlooping on startup when it is not unusual for CRDs to take longer than 7 seconds to appear.
/kind feature
```release-note
Add --retry-crd-interval-max flag to the snapshot-controller in order to allow customization of CRD detection on startup.
```
/assign @msau42
=> Parameterize startup CRD wait retries

.github/workflows/dependabot.yaml
Additional note for reviewer:
external-provisioner already have this github action. 
https://github.com/kubernetes-csi/external-provisioner/blob/master/.github/dependabot.yaml
/kind cleanup
```release-note
NONE
```
=> add dependabot configuration to github actions for auto update PRs

deploy/kubernetes/webhook-example/webhook.yaml
Kubernetes has a builtin Secret type `kubernetes.io/tls` which uses the keys `tls.crt` and `tls.key`.
With this change, when you download the example `webhook.yaml`, it's immediately compatible with secrets created e.g. by cert-manager. The downloaded file can be integrated into kustomize projects without further modification or patches.
```release-note
Change webhook example to be compatible with TLS-type secrets.
```
=> Make webhook example compatible with TLS secrets

deploy/kubernetes/webhook-example/create-cert.sh
After bb957259da3b the script was broken. This commit fixes this by respecting the format of TLS-type secrets in the script, too.
/kind bug
No release note needed as the breaking commit is not yet released.
```release-note
Fixes an issue introduced by PR 793 by respecting the format of TLS-type secrets in the script.
```
=> fix certificate generation in webhook example

deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
/kind feature
This PR adds a marker to the snapshot-controller manifests. This is needed to enable feature gates in CSI prow jobs. In https://github.com/kubernetes-csi/csi-release-tools/pull/209, the snapshot-controller YAML is updated to add `--prevent-volume-mode-conversion=true` so that the feature can be enabled for certain e2e tests. 
Also related to https://github.com/kubernetes-csi/csi-driver-host-path/pull/379
Fixes #
```release-note
Add a marker to the snapshot-controller manifests to enable feature gates in CSI prow jobs.
```
=> Add volume mode conversion flag to snapshot-controller manifest

go.mod, pkg/snapshotter/snapshotter.go, pkg/snapshotter/snapshotter_test.go
/kind cleanup
This PR removes an explicit dependency on a deprecated package
Fixes #804
This is my first K8s PR so any constructive criticism would be welcome. Thanks!
```release-note
NONE
```
=> Switch to using google.golang.org/protobuf rather than github.com/golang/protobuf

deploy/kubernetes/webhook-example/admission-configuration-template, deploy/kubernetes/webhook-example/rbac-snapshot-webhook.yaml, pkg/utils/util.go, pkg/validation-webhook/groupsnapshot.go, pkg/validation-webhook/groupsnapshot_test.go, pkg/validation-webhook/snapshot.go, pkg/validation-webhook/snapshot_test.go, pkg/validation-webhook/validation.go, pkg/validation-webhook/webhook.go, pkg/validation-webhook/webhook_test.go
/kind feature
Adds support for webhooks for  groupsnapshot CRs.
KEP - https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/3476-volume-group-snapshot
Fixes #
```release-note
Webhooks for VolumeGroupSnapshot, VolumeGroupSnapshotContent and VolumeGroupSnapshotClass.
```
/cc @xing-yang @nixpanic @RaunakShah
=> add groupsnapshot related webhooks

CHANGELOG/CHANGELOG-6.2.md
Fixes #
```release-note
NONE
```
=> Add changelog for 6.2.2.

pkg/sidecar-controller/snapshot_controller_base.go
Signed-off-by: Sameer Shaikh [sameer.shaikh@ibm.com](mailto:sameer.shaikh@ibm.com)
/kind bug
external-snapshotter constantly retrying CreateSnapshot calls on error w/o backoff
Fixes #778
@xing-yang @zhucan @pwschuurman 
ResourceEventHandlerFuncs is a implementation of ResourceEventHandler, whose method OnUpdate has the following documentation:
[external-snapshotter/vendor/k8s.io/client-go/tools/cache/controller.go](https://github.com/kubernetes-csi/external-snapshotter/blob/e746d0717a32109d8c57cb76a70b299ec849f54d/vendor/k8s.io/client-go/tools/cache/controller.go#L203-L208)
```
//  * OnUpdate is called when an object is modified. Note that oldObj is …
```
=> external-snapshotter constantly retrying CreateSnapshot calls on error w/o backoff

client/apis/volumegroupsnapshot/v1alpha1/types.go, client/config/crd/groupsnapshot.storage.k8s.io_volumegroupsnapshotclasses.yaml, client/config/crd/groupsnapshot.storage.k8s.io_volumegroupsnapshotcontents.yaml, client/config/crd/groupsnapshot.storage.k8s.io_volumegroupsnapshots.yaml
/kind feature
add more detail printed columns when exec kubectl get vgs | vgsc | vgsclass  
before
<pre>
[root@node-1 deploy]# kubectl get vgsc
NAME                                                    AGE
groupsnapcontent-03314fd3-faa5-4aea-a14b-416b8b47ba86   4h24m
[root@node-1 deploy]# kubectl get vgs
NAME                AGE
hostpath-mock-vgs   4h24m
[root@node-1 deploy]# kubectl get vgsc
NAME                                                    AGE
groupsnapcontent-03314fd3-faa5-4aea-a14b-416b8b47ba86   4h24m
</pre>
after
<pre>
[root@node-1 new-crd]# kubectl get vgsclass
NAME                 DRIVER                DELETIONPOLICY   AGE
hostpath-mock-vgsc   hostpath.csi.ake.io   Delete           4d6h
[root@node-1 new-crd]# …
=> Add more detail in vgs/vgsc/vgsclass printed columns

pkg/metrics/metrics_test.go, pkg/validation-webhook/webhook.go
>
"io/ioutil" has been deprecated since Go 1.19: As of Go 1.16
Fixes #
```release-note
NONE
```
=> chore: remove refs to deprecated io/ioutil

CHANGELOG/CHANGELOG-6.3.md
Fixes #
```release-note
NONE
```
=> Add changelog for v6.3.0

pkg/common-controller/snapshot_controller.go, pkg/common-controller/snapshot_finalizer_test.go, pkg/sidecar-controller/snapshot_controller.go, pkg/sidecar-controller/snapshot_delete_test.go
/kind bug
This PR replaces the Update calls for VolumeSnapshot and VolumeSnapshotContent with JSON patch calls. Addresses the "object has been modified" issue we see a lot in the snapshot-controller/snapshotter.
Partial fix (only for Update() calls) https://github.com/kubernetes-csi/external-snapshotter/issues/748
N/A
```release-note
Update VolumeSnapshot and VolumeSnapshotContent using JSON patch
```
=> Update VolumeSnapshot and VolumeSnapshotContent using JSON patch

deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml, deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml, deploy/kubernetes/webhook-example/webhook.yaml
>
> /kind bug
> /kind design
> /kind flake
/kind cleanup
Adopt kubernetes recommand label
Fixes #843
None
```release-note
Adopt Kubernetes recommended label "app.kubernetes.io/name" when deploying csi-snapshotter, snapshot-controller, and snapshot-validation-webhook.
```
=> chore: Adopt kubernetes recommand label

deploy/kubernetes/webhook-example/webhook.yaml, pkg/validation-webhook/webhook.go
/kind bug
VolumeGroupSnapshots are still in alpha.
This commit adds cmdline args to enable group snapshot webhooks while keeping it disbaled by default.
Fixes #921 
yes,
```release-note
Webhooks for group snapshot CRs will be disabled by default. Command line argument `enable-volume-group-snapshot-webhook` needs to be added to enable these webhooks.
```
/cc @xing-yang
=> add cmdline args to enable group snapshot webhooks

client/config/crd/groupsnapshot.storage.k8s.io_volumegroupsnapshotclasses.yaml, client/config/crd/groupsnapshot.storage.k8s.io_volumegroupsnapshotcontents.yaml, client/config/crd/groupsnapshot.storage.k8s.io_volumegroupsnapshots.yaml, client/config/crd/snapshot.storage.k8s.io_volumesnapshotclasses.yaml, client/config/crd/snapshot.storage.k8s.io_volumesnapshotcontents.yaml, client/config/crd/snapshot.storage.k8s.io_volumesnapshots.yaml, client/hack/README.md
/kind bug
The CRD yaml files in client/config/crd ([e.g.](https://github.com/kubernetes-csi/external-snapshotter/blob/master/client/config/crd/snapshot.storage.k8s.io_volumesnapshotclasses.yaml)) do not allow for standard metadata, according to their schemae.
However, looking at the struct definitions under client/apis ([e.g.](https://github.com/kubernetes-csi/external-snapshotter/blob/master/client/apis/volumesnapshot/v1/types.go#LL211C4-L211C4)), they correctly embed (and thus support) metav1.ObjectMeta -- and the docs reflect this as well.
This isn't problematic at first glance, because the controller recognizes and knows how to handle ObjectMeta in an applied resource. We only noticed it because we have a CI linter …
=> Fix CRDs missing metadata fields

cmd/snapshot-controller/main.go, deploy/kubernetes/csi-snapshotter/rbac-csi-snapshotter.yaml, deploy/kubernetes/snapshot-controller/rbac-snapshot-controller.yaml, pkg/common-controller/groupsnapshot_controller_helper.go, pkg/common-controller/snapshot_controller.go, pkg/common-controller/snapshot_controller_base.go, pkg/group_snapshotter/group_snapshotter.go, pkg/sidecar-controller/csi_handler.go, pkg/sidecar-controller/groupsnapshot_helper.go, pkg/utils/patch.go, pkg/utils/util.go
/kind feature
This PR adds logic to delete volume group snapshots. 
Currently, Only the volume group snapshots and corresponding volume group snapshot contents are deleted. The logic to delete individual snapshots will be added in a separate PR.
**Testing**
1. Dynamically volume group snapshot:
- Create a volume group snapshot 
```
% kubectl create -f volumegroupsnapshot-example.yaml 
volumegroupsnapshot.groupsnapshot.storage.k8s.io/my-group-snapshot created
% kubectl get vgsc
NAME                                                    READYTOUSE   DELETIONPOLICY   DRIVER                VOLUMEGROUPSNAPSHOTCLASS   VOLUMEGROUPSNAPSHOTNAMESPACE   VOLUMEGROUPSNAPSHOT   AGE
groupsnapcontent-29f97dbc-d2a7-4204-b356-98a8c29870fb …
```
=> DeleteVolumeGroupSnapshot API - part 1

deploy/kubernetes/snapshot-controller/rbac-snapshot-controller.yaml
This patch allows the snapshot-controller-runner ClusterRole, bound to the snapshot-controller Service Account, to delete VolumeSnapshot objects. This is needed during the VolumeGroupSnapshot deletion.
/kind bug
```release-note
NONE
```
=> Allow snapshot controller to delete VolumeSnapshots

examples/kubernetes/groupsnapshot-v1alpha1.yaml, examples/kubernetes/groupsnapshotclass-v1alpha1.yaml
This PR adds two examples of how a VolumeGroupSnapshotClass and a VolumeGroupSnapshot can be defined.
The examples use the CSI Hostpath Driver.
Fixes #
NONE
```release-note
NONE
```
=> Add VolumeGroupSnaphot examples

README.md, cmd/snapshot-controller/main.go, pkg/validation-webhook/webhook.go
>
> /kind bug
> /kind design
/kind feature
> /kind flake
This is beta since 1.27 so we can safely default to true, to get this new validation logic. https://github.com/kubernetes/enhancements/blob/master/keps/sig-storage/3141-prevent-volume-mode-conversion/kep.yaml#L30
Fixes #
```release-note
Enable prevent-volume-mode-conversion feature flag by default.
ACTION REQUIRED: 
Volume mode change will be …
```
=> Enable prevent-volume-mode-conversion by default following k8s 1.28 release

README.md, cmd/snapshot-controller/main.go, deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
/kind bug
Based on my understanding of the flag `retry-crd-interval-max` (see #980), this PR will ensure that the function `ensureCustomResourceDefinitionsExist` returns when the duration specified in `retryCRDIntervalMax` flag is reached. This works using by passing a context to the backoff so that we can simply timeout with context.WithTimeout (and not too complicated computations that may or may not do what we want).
Also limit the amount of resources returned by the list calls to 0 to speed up the operations because we only care that the CRD exists and not about the number of results.
It changes the default value of the flag to `30s` for 2 reasons:
- the timeout includes a bunch network calls to the apiserver. …
=> Fix the max duration to wait for CRDs in the snapshot-controller

pkg/group_snapshotter/group_snapshotter.go, pkg/sidecar-controller/csi_handler.go, pkg/sidecar-controller/groupsnapshot_helper.go
/kind feature
GroupSnapshots are not fully implemented yet.
The commit in this PR makes it work nicely:
```yaml
---
apiVersion: groupsnapshot.storage.k8s.io/v1alpha1
kind: VolumeGroupSnapshotContent
metadata:
name: manual-vgs-content
spec:
deletionPolicy: Retain
driver: hostpath.csi.k8s.io
volumeGroupSnapshotRef:
apiVersion: groupsnapshot.storage.k8s.io/v1alpha1
kind: VolumeGroupSnapshot
name: manual-vgs
namespace: default
volumeGroupSnapshotClassName: csi-hostpath-vgsc
source:
groupSnapshotHandles:
volumeGroupSnapshotHandle: 41a78530-bb86-11ee-93b4-0a580a810320
volumeSnapshotHandles:
- 41a78c22-bb86-11ee-93b4-0a580a810320
---
apiVersion: groupsnapshot.storage.k8s.io/v1alpha1
kind: VolumeGroupSnapshot
metadata:
name: …
```
=> implement GroupSnapshotter.GetGroupSnapshotStatus()

pkg/validation-webhook/snapshot.go
/kind bug
This PR adds a nil check for SourceVolumeMode in the snapshot validation webhook.
Fixes #1003 
```release-note
Fixes a panic in the snapshot validation webhook.
```
=> Add nil check for SourceVolumeMode in the validation webhook

pkg/validation-webhook/snapshot.go
(cherry picked from commit 36738cd8bc99a39149db514ea95f1e317d119546)
/kind bug
Fixes #
```release-note
Cherry-pick from PR [#1005](https://github.com/kubernetes-csi/external-snapshotter/pull/1005). Fixes a panic in the snapshot validation webhook.
```
=> Add nil check for SourceVolumeMode in the ValidationWebHook

pkg/sidecar-controller/groupsnapshot_helper.go, pkg/sidecar-controller/snapshot_controller.go
Currently the RestoreSize is missing when the corresponding VSC are created for the the volumesnapshotgroup, This PR adds the missing RestoreSize for VSC.
>
/kind bug
> /kind design
> /kind flake
Fixes #1002
```release-note
This change will update the Restore size in volumesnapshotcontent to the size it's received from the CSI driver. If `0` is received, it won't be added to the Restore …
```
=> Add snapshot size to VSC created for VGS

pkg/common-controller/groupsnapshot_controller_helper.go, pkg/sidecar-controller/groupsnapshot_helper.go
Fix logging in the volumegroupsnapshot methods and also use `GroupSnapshotDeleteError` event type for delete volumegroupsnapshot failures
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Fixes #
```release-note
None
```
=> Fix logging in the volumegroupsnapshot methods

pkg/common-controller/groupsnapshot_controller_helper.go, pkg/common-controller/snapshot_controller.go, pkg/utils/util.go, pkg/utils/util_test.go
>
/kind bug
> /kind design
> /kind flake
The annotation to use the selected VolumeGroupSnapshotClass by default is expected to be `groupsnapshot.storage.kubernetes.io/is-default-class=true`, but the check was done on `snapshot.storage.kubernetes.io/is-default-class` instead.
Fixes #968
```release-note
Adding the annotation `groupsnapshot.storage.kubernetes.io/is-default-class=true` on a …
```
=> Fix detecting default annotation on VolumeGroupSnapshotClass

pkg/sidecar-controller/snapshot_controller_base.go, pkg/utils/util.go, pkg/utils/util_test.go
/kind bug
In many scenarios, the `csi-snapshotter` sidecar will enqueue a `VolumeSnapshotContent` object in rapid succession, causing a flood of RPC requests to the attached CSI Driver.
The most user-visible subset of this, when the CSI driver fails the request, has been reported and attempted to be fixed twice: #463 and #778. However, neither of the fixes completely fix the issue, *which occurs even when the CSI driver does not return an error*.
The most basic and common version of this issue is as follows:
1. A `VolumeSnapshotContent` object is enqueued (for example, because it is created)
2. Very early on in this process, the `csi-snapshotter` will update the status of the content …
=> Discard unnecessary VolumeSnapshotContent updates to prevent rapid RPC calls

pkg/common-controller/groupsnapshot_controller_helper.go, pkg/sidecar-controller/groupsnapshot_helper.go, pkg/utils/util.go
Fixes: https://github.com/kubernetes-csi/external-snapshotter/issues/834
>
> /kind bug
> /kind design
/kind feature
> /kind flake
**What this PR does / why we need it**: 
Adds secret reference to group snapshots
**Which issue(s) this PR fixes**:  
*Automatically closes linked issue when PR is merged.
Usage: `Fixes #<issue number>`, or `Fixes (paste link of issue)`.
_If PR is about `failing-tests or flakes`, please post the related issues/tests in a comment and do not use `Fixes`_*
-->
Fixes #834
**Does this PR introduce a …
=> Add snapshot secret reference to group snapshot controller.

pkg/common-controller/groupsnapshot_controller_helper.go, pkg/sidecar-controller/groupsnapshot_helper.go
This is the backport of https://github.com/kubernetes-csi/external-snapshotter/pull/1014 
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Fixes #
```release-note
Cherry-pick from PR [#1014](https://github.com/kubernetes-csi/external-snapshotter/pull/1014)
```
=> [release-7.0]: Fix logging in the volumegroupsnapshot methods

pkg/sidecar-controller/groupsnapshot_helper.go, pkg/sidecar-controller/snapshot_controller.go
Currently the RestoreSize is missing when
the corresponding VSC are created for the
the volumesnapshotgroup, This PR adds the missing
RestoreSize for VSC.
Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>
(cherry picked from commit 5a7115d61de02905b540bff64c671a3c2f891216)
>
/kind bug
> /kind design
> /kind flake
Fixes #
```release-note
Cherry-pick from PR …
```
=> [release-7.0] Add snapshot size to VSC created for VGS

pkg/group_snapshotter/group_snapshotter.go, pkg/sidecar-controller/csi_handler.go, pkg/sidecar-controller/groupsnapshot_helper.go
>
/kind bug
> /kind design
> /kind flake
GetGroupSnapshotStatus is a group operation on a specific group with an ID, we can use the group specific secret instead of List operation specific secret.
Fixes #
```release-note
Use Group secret for the GetGroupSnapshotStatus RPC call
```
=> use group secret for GetGroupSnapshotStatus

pkg/common-controller/framework_test.go, pkg/common-controller/snapshot_controller.go, pkg/sidecar-controller/groupsnapshot_helper.go, pkg/sidecar-controller/snapshot_controller.go, pkg/utils/util.go, pkg/utils/util_test.go
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
With Go 1.21 the "slices" package can be used for many operations on slices. The custom ContainsString() function can be replaced by the standard slices.Contains().
Fixes #
```release-note
NONE
```
=> replace custom ContainsString() with standard slices.Contains()

pkg/sidecar-controller/snapshot_controller.go
This patch replace the usage of `UpdateStatus` with a patch against the `status` subresource in the `updateSnapshotContentStatus`.
The reason behind this change is to avoid conflicts that could potentially arise, as they pose a risk within the context of the calling function `createGroupSnapshotWrapper`.
If `createGroupSnapshotWrapper` is called multiple times for the same GroupSnapshot, this will lead to multiple stale `VolumeSnapshot` and `VolumeSnapshotContent` being created.
Related: #1050
>
/kind bug
> /kind design
> /kind flake
**What this …
=> Avoid conflicts in updateSnapshotContentStatus

pkg/common-controller/groupsnapshot_controller_helper.go
>
/kind bug
> /kind design
> /kind flake
This PR avoids the external-snapshotter controller from panicking when the user requests a VolumeGroupSnapshot across non-CSI PVs.
In my tests, `master` was failing with:
```
goroutine 124 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc0000f8800?})
/Users/leonardo.cecchi/go/src/github.com/kubernetes-csi/external-snapshotter/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:56 +0xcd
panic({0x17ff940?, 0x29eba50?}) …
```
=> Avoid panicking when snapshotting a non-CSI PV

client/apis/volumegroupsnapshot/v1alpha1/types.go, client/apis/volumesnapshot/v1/types.go
/kind feature
This is to add validation rules to CRDs which did the same validation as written in https://github.com/kubernetes-csi/external-snapshotter/blob/master/pkg/validation-webhook/validation.go
Fixes #1072 
The feature is available since Kubernetes 1.25. Is there any version compatibility concern there? Could I remove the existing validating webhook in the same PR? Thank you!
```release-note
Adds validation rules into CRDs. Minimum required Kubernetes version is 1.25 for these validation rules.
```
=> Adding validation rules into CRDs for validation

Makefile, client/go.mod, hack/verify-vendor.sh
/kind cleanup
As observed in the PR below, the current vendor tests might not always detect if go mod tidy or similar commands have been run in the external-snapshotter when changes are made in the client module.
https://github.com/kubernetes-csi/external-snapshotter/pull/1073
To address this, in this PR, I have made the following enhancements:
1. Added vendor checks for the client module
2. Enhanced vendor checks for the external-snapshotter
These changes aim to reduce the risk of vendor updates being overlooked.
refs:
- https://github.com/kubernetes-csi/external-snapshotter/pull/1084
- https://github.com/kubernetes-csi/csi-release-tools/pull/252#issuecomment-2105144487
Fixes # …
=> Ensure vendor checks are run for all modules

client/hack/README.md, client/hack/update-generated-code.sh
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
code-generator/generate-groups.sh is no longer worker in 1.30.
Use code-generator/kube_codegen.sh instead.
Fixes #
```release-note
Replace code-generator/generate-groups.sh with code-generator/kube_codegen.sh in update-generated-code.sh.
```
=> Update code-generator to 1.30.0

client/config/crd/groupsnapshot.storage.k8s.io_volumegroupsnapshotclasses.yaml, client/config/crd/groupsnapshot.storage.k8s.io_volumegroupsnapshotcontents.yaml, client/config/crd/groupsnapshot.storage.k8s.io_volumegroupsnapshots.yaml, client/config/crd/snapshot.storage.k8s.io_volumesnapshotclasses.yaml, client/config/crd/snapshot.storage.k8s.io_volumesnapshotcontents.yaml, client/config/crd/snapshot.storage.k8s.io_volumesnapshots.yaml, client/hack/README.md, client/hack/update-crd.sh
>
> /kind bug
> /kind design
> /kind flake
Update manifests with controller-gen@v0.15.0 and validation rules added by https://github.com/kubernetes-csi/external-snapshotter/pull/1073.
Fixes #
This PR depends on https://github.com/kubernetes-csi/external-snapshotter/pull/1073.
```release-note
Update manifests with controller-gen@v0.15.0 and new validation rules. Minimum required Kubernetes …
```
=> Update manifests based on new CRD validation rules

pkg/common-controller/groupsnapshot_controller_helper.go, pkg/sidecar-controller/groupsnapshot_helper.go, pkg/utils/pvs.go, pkg/utils/pvs_test.go
>
> /kind bug
> /kind design
/kind feature
> /kind flake
Following #1068 and the discussion in #969, this PR improves the snapshot controller and the CSI snapshotter sidecar to track which PVC and PVs are snapshotted by a VolumeGroupSnapshot.
With this PR applied, a `VolumeGroupSnapshot` will look like:
```
apiVersion: groupsnapshot.storage.k8s.io/v1alpha1
kind: VolumeGroupSnapshot
metadata:
finalizers:
- groupsnapshot.storage.kubernetes.io/volumegroupsnapshot-bound-protection
generation: 1
name: new-groupsnapshot …
```
=> Link PVCs and PVs in VolumeGroupSnapshot and VolumeGroupSnapshotContent

client/apis/volumesnapshot/v1/types.go, client/config/crd/snapshot.storage.k8s.io_volumesnapshotcontents.yaml, client/hack/README.md, pkg/utils/patch.go, vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/apis/volumesnapshot/v1/types.go
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Fixes #
```release-note
The Namespace additional printer column is now generated from a marker in the codebase instead of directly added in the CRD.
```
=> Use a marker for the Namespace VSC additional printer column

CHANGELOG/CHANGELOG-8.0.md, CHANGELOG/release-notes-1496540165
>
> /kind bug
> /kind design
> /kind flake
This PR adds changelog for v8.0.
Fixes #
```release-note
NONE
```
=> Add changelog for v8.0

pkg/common-controller/groupsnapshot_controller_helper.go, pkg/metrics/metrics.go, pkg/metrics/metrics_group.go, pkg/metrics/metrics_test.go
This PR introduces new operation like CreateGroupsnapshot, DeleteGroupsnapshots, etc to the existing metrics
**Testing**
* enable feature gate for groupvolumesnapshot 
* pass --http-endpoint to include the port to expose the metrics
* curl using the port and metrics path
**TODO**
Add output for deleteGroupSnapshot operation 
Fixes # 1081
n/a
```release-note
it exposes the metrics for volumegroupsnapshot operations on passing flags like --http-endpoint and --metrics-path to the snapshot controller. These are the command line arguments for the users to enable metrics and start the sever. …
```
=> Add group snapshot controller metrics

pkg/common-controller/groupsnapshot_controller_helper.go
>
/kind bug
> /kind design
> /kind flake
Check whether the volumes to be snapshotted in a group belong to the CSI driver referenced in the VolumeGroupSnapshot resource.
Fixes #1096
```release-note
Prevents a VolumeGroupSnapshot to be provisioned when the volumes' CSI driver is different from the one referenced in the VolumeGroupSnapshotClass resource
```
=> Avoid group snapshot provisioning with mismatching CSI Drivers

pkg/common-controller/groupsnapshot_controller_helper.go, pkg/common-controller/snapshot_controller.go, pkg/utils/util.go, pkg/utils/util_test.go
/kind bug
>
> /kind design
> /kind flake
This PR makes the controller process newly created default VolumeSnapshotClasses and VolumeGroupSnapshotClasses, correctly using them or raising an error when appropriate.
Fixes #1099 
The controller is using an informer to get VolumeGroupSnapshotClasses and VolumeSnapshotClasses.
Unfortunately, objects returned by that will not have the API Kind info set (see …
=> Correctly detect newly created Volume[Group]SnapshotClasses

README.md, client/config/crd/kustomization.yaml
>
> /kind bug
> /kind design
> /kind flake
Mention volume group snapshots in the README file
Fixes #1117
This PR changes `client/config/crd/kustomization.yaml` to install the VolumeGroupSnapshots CRDs at the same time as the VolumeSnapshot CRDs. To we want to do that? Otherwise, we can continue requiring a separate installation.
In that case, I'll change the README to document that step too. …
=> Document Volume Group Snapshot feature in the README file

pkg/common-controller/groupsnapshot_controller_helper.go
>
/kind bug
> /kind design
> /kind flake
When looking for the name of the CSI driver to use for a volume group snapshot, we were looking for a VolumeSnapshotClass instead of a VolumeGroupSnapshotClass. This made the VolumeGroupSnapshot fail when there is no such VolumeGroupSnapshotClass.
Fixes #
```release-note
Look for a VolumeGroupSnapshotClass instead of a VolumeSnapshotClass when …
```
=> Look for a VolumeGroupSnapshotClass when getting the class of a VolumeGroupSnapshot

pkg/common-controller/framework_test.go, pkg/common-controller/groupsnapshot_controller_helper.go, pkg/common-controller/groupsnapshot_create_test.go, pkg/common-controller/groupsnapshot_delete_test.go, pkg/common-controller/groupsnapshot_finalizer_test.go, pkg/common-controller/groupsnapshot_update_test.go, pkg/common-controller/snapshot_create_test.go, pkg/common-controller/snapshot_delete_test.go, pkg/common-controller/snapshot_finalizer_test.go, pkg/common-controller/snapshot_update_test.go
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Adds unit tests for the group snapshot controller.
Fixes #1082
```release-note
NONE
```
=> Add group snapshot controller unit tests

pkg/common-controller/snapshot_controller.go, vendor/k8s.io/client-go/util/retry/OWNERS, vendor/k8s.io/client-go/util/retry/util.go, vendor/modules.txt
> /kind bug
The previous `removePVCFinalizer` function was using the PVC stored in the informer which, in cases where the PVC had been modified since, lead to conflict errors when trying to remove the PVC finalizer through an update.
Example error:
```
E0807 13:09:20.573657       1 snapshot_controller.go:183] error check and remove PVC finalizer for snapshot [snapshot]: snapshot controller failed to update pvc-sts-0 on API server: Operation cannot be fulfilled on persistentvolumeclaims "pvc-sts-0": the object has been modified; please apply your changes to the latest version and try again
```
Unfortunately, the error was not retried so the PVC ends up stuck.
Now the `removePVCFinalizer` function uses the …
=> [snapshot-controller] Retry PVC finalizer removal on conflict

cmd/csi-snapshotter/main.go, cmd/snapshot-controller/main.go
/kind feature
If not specified explicitly, JSON encoding is used by default when talking to kube-apiserver.
For core K8s API objects like Pods, Nodes, etc., we can use protobuf encoding which reduces CPU consumption related to (de)serialization, reduces overall latency of the API call, reduces memory footprint, reduces the amount of work performed by the GC and results in quicker propagation of objects to event handlers of shared informers.
For CRDs, however, we still have to stick to JSON since they do not support protobuf encoding.
No issue is opened for that.
Standard system components of K8s default their serialization method to protobuf for some …
=> Use protobuf encoding for core K8s APIs in external-snapshotter

.github/workflows/trivy.yaml, go.mod
```
csi-snapshotter (gobinary)
==========================
Total: 3 (UNKNOWN: 0, LOW: 0, MEDIUM: 2, HIGH: 1, CRITICAL: 0)
┌─────────┬────────────────┬──────────┬────────┬───────────────────┬────────────────┬─────────────────────────────────────────────────────────────┐
│ Library │ Vulnerability  │ Severity │ Status │ Installed Version │ Fixed Version  │                            Title                            │
├─────────┼────────────────┼──────────┼────────┼───────────────────┼────────────────┼─────────────────────────────────────────────────────────────┤
│ stdlib  │ CVE-2024-[34](https://github.com/kubernetes-csi/external-snapshotter/actions/runs/10772342121/job/29869769539?pr=1155#step:6:35)156 │ HIGH     │ fixed  │ 1.22.5            │ …
```
=> test: fix trivy github action error

client/apis/volumegroupsnapshot/v1alpha1/types.go, client/config/crd/groupsnapshot.storage.k8s.io_volumegroupsnapshotcontents.yaml, vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/apis/volumegroupsnapshot/v1alpha1/types.go
>
/kind bug
> /kind design
> /kind flake
We need to remove the validation rule that ensures volumeGroupSnapshotRef is immutable. 
This is because that UID needs to be set by the snapshot controller after volumeGroupSnapshotRef is populated with name and namespace for pre-provisioned VolumeGroupSnapshotContent.
This immutable validation rule was added as part of this PR https://github.com/kubernetes-csi/external-snapshotter/pull/1073 to use CEL to replace the validation added in the validation webhook:
```
// …
```
=> Remove volumeGroupSnapshotRef immutable validation rule

pkg/common-controller/groupsnapshot_controller_helper.go, pkg/common-controller/snapshot_controller.go
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
This patch sets the `spec.persistentVolumeClaimName` field for
volume snapshots that are members of a dynamically provisioned volume
group snapshot, like a dynamically provisioned volume snapshot would do.
The volume snapshot logic has been improved to skip the creation of
relative snapshot as it has already been created by the group snapshot.
Fixes #
**Does this PR introduce a user-facing …
=> Set PVC name on VolumeGroupSnapshot members

pkg/sidecar-controller/groupsnapshot_helper.go, pkg/utils/util.go
this commit adds new parameter keys for
getvolumegroupsnapshot
Ref: https://github.com/kubernetes-csi/external-snapshotter/issues/1122#issuecomment-2436739611 
```release-note
Add VolumeGroupSnapshotClass secrets for GetVolumeGroupSnapshot.
```
=> Add secrets for Get VolumeGroupSnapshot

pkg/common-controller/framework_test.go, pkg/common-controller/groupsnapshot_controller_helper.go, pkg/common-controller/snapshot_controller_base.go
>
> /kind bug
kind cleanup
> /kind design
> /kind flake
Address a TODO comment.
Updates #1171
TODO note added by @leonardoce.
The sync operations are triggered from a work queue, so there are no real contexts related to the original request. A single context is now created and passed on from the work queue function.
```release-note
NONE
```
=> Pass context on in GroupSnapshot sync functions

pkg/common-controller/groupsnapshot_controller_helper.go, pkg/sidecar-controller/snapshot_controller.go, pkg/utils/util.go
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
This patch sets the `spec.source.volumeHandle` field for
volume snapshot contents that are members of a dynamically provisioned volume
group snapshot, like a dynamically provisioned volume snapshot content would do.
The volume snapshot content logic has been improved to consider this case too.
Fixes #
```release-note
The "spec.source.volumeHandle" …
```
=> Set VolumeHandle for dynamically provisioned VolumeGroupSnapshots

client/apis/volumegroupsnapshot/v1alpha1/types.go, client/apis/volumegroupsnapshot/v1alpha1/zz_generated.deepcopy.go, client/config/crd/groupsnapshot.storage.k8s.io_volumegroupsnapshots.yaml, pkg/common-controller/groupsnapshot_controller_helper.go, pkg/utils/util.go, vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/apis/volumegroupsnapshot/v1alpha1/types.go, vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/apis/volumegroupsnapshot/v1alpha1/zz_generated.deepcopy.go
>
> /kind bug
> /kind design
> /kind flake
This PR removes the `PVCVolumeSnapshotRefList` entry from the VolumeGroupSnapshot API. This is no longer needed since we now set `persistentVolumeClaimName` in the source of member VolumeSnapshots
Fixes #1202 
```release-note
The `volumegroupsnapshot.status.pvcVolumeSnapshotRefList` field has been removed. VolumeShapshots members of a dynamically …
```
=> Remove PVCVolumeSnapshotRefList from VolumeGroupSnapshot API

pkg/sidecar-controller/snapshot_controller.go
>
/kind bug
> /kind design
> /kind flake
Fixes #1203 
```release-note
Only dynamic provisioning for an independent snapshot needs a snapshot class. A member snapshot in a dynamically provisioned volume group snapshot does not need a snapshot class.
```
=> Only dynamic provisioning for an independent snapshot needs a snapshot class

go.mod, go.sum, vendor/modules.txt
this commit updates CSI spec to have official
release verison v1.11.0
```release-note
use v1.11.o version of CSI spec
```
=> update CSI spec to have official version

pkg/sidecar-controller/snapshot_controller.go
>
/kind bug
> /kind design
> /kind flake
Fixes #1203
```release-note
NONE
```
=> Do not panic when a default snapshotclass does not exist

pkg/common-controller/groupsnapshot_controller_helper.go
>
/kind bug
> /kind design
> /kind flake
Fixes #1214
```release-note
Fixed a race condition happening when deleting dynamically provisioned a VolumeGroupSnapshot whose DeletionPolicy is set to "Retain"
```
=> Prevent infinite loop deleting group snapshots

pkg/common-controller/groupsnapshot_controller_helper.go, pkg/sidecar-controller/snapshot_controller.go, pkg/utils/util.go
>
/kind bug
> /kind design
> /kind flake
use annotation instead of label to storage the groupsnapshot handle to avoid length limit
Fixes #1218
```release-note
Store the volumegroupsnapshot handle as a annotation in the volumesnapshotcontent instead of labels as label values are restricted to 63 chars
```
=> use annotation to store the groupsnapshot handle

pkg/common-controller/groupsnapshot_controller_helper.go
>
/kind bug
> /kind design
> /kind flake
Add the error checking for group snapshot members when processing a group snapshot deletion.
Fixes #
```release-note
NONE
```
=> Add error checking to processGroupSnapshotWithDeletionTimestamp

pkg/common-controller/groupsnapshot_controller_helper.go
>
/kind bug
> /kind design
> /kind flake
This PR improves the common snapshot controller to introduce the bound finalizer on VolumeGroupSnapshots that have been dynamically provisioned with `DeletionPolicy` being `Retain`.
This allows the controller to set the required annotation in the VolumeGroupSnapshotContent object.
See the issue for a more in-depth discussion.
Fixes #1212 …
=> Add the group snapshot bound finalizer when deletionPolicy is set to Retain

go.mod, pkg/common-controller/framework_test.go, pkg/common-controller/groupsnapshot_controller_helper.go, pkg/common-controller/snapshot_controller.go, pkg/common-controller/snapshot_controller_base.go, pkg/sidecar-controller/groupsnapshot_helper.go, pkg/utils/util.go, pkg/utils/vgs.go, pkg/utils/vgs_test.go
Instead of marking the member snapshot object with a label, this PR uses an ownership reference.
Member objects are looked up using a new index in the informer cache.
>
/kind bug
> /kind design
> /kind flake
This PR removes the usage of the `groupsnapshot.storage.k8s.io/volumeGroupSnapshotName` label, opting for an ownership-based volume group snapshot member tracking as described in [the relative comment](https://github.com/kubernetes-csi/external-snapshotter/issues/1213#issuecomment-2498764193).
The patch …
=> Use ownership to identify volume group snapshot members

README.md, cmd/csi-snapshotter/main.go
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
replace the old ref of enable-volume-group-snapshots flag with featuregate
Fixes #1227
```release-note
None
```
=> replace enable-volume-group-snapshots with featuregate

client/apis/volumegroupsnapshot/v1beta1/types.go, client/apis/volumegroupsnapshot/v1beta1/zz_generated.deepcopy.go, client/config/crd/groupsnapshot.storage.k8s.io_volumegroupsnapshotcontents.yaml, pkg/common-controller/framework_test.go, pkg/common-controller/groupsnapshot_controller_helper.go, pkg/sidecar-controller/groupsnapshot_helper.go, vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/apis/volumegroupsnapshot/v1beta1/types.go, vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/apis/volumegroupsnapshot/v1beta1/zz_generated.deepcopy.go
>
> /kind bug
> /kind design
> /kind flake
Fixes #1234
```release-note
`VolumeGroupSnapshotContent.status.creationTime` is now a metav1.Time instead of an unix epoch time
```
=> Change CreationTime in VolumeGroupSnapshotContentStatus from *int64 to *metav1.Time

cmd/snapshot-controller/main.go
>
/kind bug
> /kind design
> /kind flake
As of v6.2.2, the snapshot controller performs a list operation on startup as a way of validating the Snapshot CRD is installed on the cluster. v7.0.0 attempts to put a limit on this list call of 0, but [that is treated as an unbounded request by etcd](https://github.com/kubernetes/kubernetes/blob/249ad2a6137cc8f1e0ccb7f0aef9ff4ba38927b9/vendor/go.etcd.io/etcd/client/v3/kubernetes/interface.go#L75). 
For clusters with many VolumeSnapshots, the API Server may struggle …
=> Fix Snapshot Controller's unbounded VolumeSnapshot list call on startup

pkg/sidecar-controller/groupsnapshot_helper.go, pkg/sidecar-controller/groupsnapshot_helper_test.go
- Add a check to ensure `groupSnapshotContent` is not nil in `deleteCSIGroupSnapshotOperation` to prevent panics.
- Enhance error handling for missing `SnapshotHandle` in `VolumeSnapshotContent` objects during deletion.
- Create initial unit tests in `groupsnapshot_helper_test.go` to cover cases where `groupSnapshotContent` is nil or incomplete.
>
/kind bug
> /kind design
> /kind flake
Before fix:
```bash
[Running: /usr/local/go/bin/go test -timeout 30s -run ^TestDeleteCSIGroupSnapshotOperation$ …
```
=> Add nil check for groupSnapshotContent in deleteCSIGroupSnapshotOperaion and unit tests

.github/workflows/trivy.yaml, CHANGELOG/CHANGELOG-8.1.md, go.mod, go.sum, release-tools/build.make, release-tools/prow.sh, release-tools/pull-test.sh, vendor/github.com/prometheus/client_golang/prometheus/histogram.go, vendor/modules.txt
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
#1242 fails due to Trivy detecting CVEs in go v1.22.5. Release-8.0 does not have these CVEs because they do not exist in go v1.22.3.
This PR:
- cherry-picks #1156 
- Updates release-tools subtree
- Fixes data race by bumping prometheus/client_golang 
```
Squashed 'release-tools/' changes from 988496a1..406a79ac
Squashed 'release-tools/' changes from 988496a1..406a79ac
Squashed 'release-tools/' changes from 988496a1..406a79ac
406a79ac Merge pull request #267 from …
```
=> [release-8.1] Bump to go v1.23.1 to fix trivy

release-tools/build.make, release-tools/cloudbuild.yaml, release-tools/prow.sh
/kind cleanup
Squashed 'release-tools/' changes from e31de525..04965932
04965932 Merge pull request #268 from huww98/cloudbuild
119aee1f Merge pull request #266 from jsafrane/bump-sanity-5.3.1
0ae5e52d Update cloudbuild image with go 1.21+
406a79ac Merge pull request #267 from huww98/gomodcache
9cec273d Set GOMODCACHE to avoid re-download toolchain
98f23071 Merge pull request #260 from TerryHowe/update-csi-driver-version
e9d8712d Merge pull request #259 from stmcginnis/deprecated-kind-kube-root
faf79ff6 Remove --kube-root deprecated kind argument
734c2b95 Merge pull request #265 from Rakshith-R/consider-main-branch
43bde065 Bump csi-sanity to 5.3.1
f95c855b Merge pull request #262 from huww98/golang-toolchain
3c8d966f Treat main branch as equivalent to master branch
6b05f0fc use new …
=> Update release tools

release-tools/cloudbuild.yaml, release-tools/prow.sh
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
See https://github.com/kubernetes-csi/external-snapshotter/pull/1247#issuecomment-2546322879
```
Squashed 'release-tools/' changes from 406a79acf..049659326
049659326 Merge pull request #268 from huww98/cloudbuild
119aee1ff Merge pull request #266 from jsafrane/bump-sanity-5.3.1
0ae5e52d9 Update cloudbuild image with go 1.21+
43bde065f Bump csi-sanity to 5.3.1
git-subtree-split: 04965932661b6e62709dcdbb9c25da528bac2605
```
**Which …
=> [release-8.1] Fix image-push by updating release-tools

pkg/common-controller/groupsnapshot_controller_helper.go
>
> /kind bug
> /kind design
> /kind flake
/kind bug
feat: use voluegroupsnapshot uid to make snapshotname
previous we use volumegroupsnapshotcontent uid and source volume to make snapshot name in volumegroupsnapshot, but in CSI it can't get volumegroupsnapshotcontent uid, but in CSI grpc request it can get volumegroupsnapshot uid by volumegroupsnapshotcontent name. Use volumegroupsnapshot uid to make snapshot name in volumegroupsnapshot may be more make sense here.
Fixes …
=> fix: use voluegroupsnapshot uid to make snapshotname

release-tools/prow.sh
/kind cleanup
Squashed 'release-tools/' changes from 90efb2ca5..0a435bf98
0a435bf98 Merge pull request https://github.com/kubernetes-csi/external-snapshotter/issues/274 from andyzhangx/patch-5
cd7b4bba3 Bump golang to 1.24.2 to fix https://github.com/advisories/GHSA-g9pc-8g42-g6vq
701dc34bc Merge pull request https://github.com/kubernetes-csi/external-snapshotter/issues/273 from andyzhangx/patch-4
aeebd30e8 Bump golang to 1.24.0
f277d561f Merge pull request https://github.com/kubernetes-csi/external-snapshotter/issues/270 from carlory/update-kind-version
6dcb96a51 update default kind version to v0.25.0
git-subtree-split: 0a435bf987dd41314377818fa26a7bed006c01cd
```
NONE
```
=> Update csi release tools

pkg/utils/util.go, pkg/utils/util_test.go
/kind bug
Resyncs are sent to an informer's update handler via a no-diff (i.e. `new` and `old` are identical) update. Currently, `ShouldEnqueueContentChange` will incorrectly return `false` in this case, as it detects no change.
We can reliably determine if an update is caused by a resync by comparing the resource versions, as any normal update will cause these to differ. This is also how the `external-attacher` handles this case in its similar `shouldEnqueueVAChange`: https://github.com/kubernetes-csi/external-attacher/blob/c8f0c14a7d985c33d8fe80a55ebb46a1ee3df877/pkg/controller/controller.go#L288-L291
Partial fix of #1258
N/A
**Does this PR …
=> Queue resyncs in `ShouldEnqueueContentChange`

go.mod
/kind cleanup
Update to go1.24.4 to fix CVEs.
https://github.com/kubernetes-csi/external-snapshotter/actions/runs/15716772540/job/44288303370
**csi-snapshotter (gobinary)**
Total: 3 (UNKNOWN: 0, LOW: 0, MEDIUM: 2, HIGH: 1, CRITICAL: 0)
stdlib  │ CVE-2025-22874 │ HIGH     │ fixed  │ v1.24.3           │ 1.24.4  
Fixes #
```release-note
NONE
```
=> Update to go1.24.4

.github/workflows/trivy.yaml
test: fix CVE-2025-47907 error in trivy action
```
csi-snapshotter (gobinary)
==========================
Total: 1 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 1, CRITICAL: 0)
┌─────────┬────────────────┬──────────┬────────┬───────────────────┬─────────────────┬────────────────────────────────────────────┐
│ Library │ Vulnerability  │ Severity │ Status │ Installed Version │  Fixed Version  │                   Title                    │
├─────────┼────────────────┼──────────┼────────┼───────────────────┼─────────────────┼────────────────────────────────────────────┤
│ stdlib  │ CVE-2025-47907 │ HIGH     │ fixed  │ v1.24.4           │ 1.23.12, 1.24.6 │ database/sql: Postgres Scan Race Condition │
│         │ …
```
=> test: fix CVE-2025-47907 error in trivy action
