kubernetes-csi/external-snapshotter

- code-of-conduct.md
This PR adds code-of-conduct.md file.
> Add code of conduct file

- OWNERS
Create OWNERS file for kubernetes-csi/external-snapshotter
xref https://github.com/kubernetes/community/issues/2467
> Create Owners files

- cmd/csi-snapshotter/create_crd.go
> cleanup remove unused code

- cmd/csi-snapshotter/main.go
- pkg/controller/snapshot_controller_base.go
> Add event scheme

- README.md
> Add more contents to readme file

- pkg/controller/snapshot_controller.go
This PR sets the snapshot class and UID in the volume snapshot
content spec if one of them is not set. This is to make sure
that snapshot class is set in the content in the case of
static binding.
> Update snapshot class in the content spec

- deploy/kubernetes/setup-csi-snapshotter.yaml
This PR updates images to v0.4.0.
> Update images to v0.4.0

- deploy/kubernetes/setup-csi-snapshotter.yaml
This PR cherry-picks the change to update images to v0.4.0 to release-0.4 branch.
> Cherry-pick update images to v0.4.0

- README.md
> fix readme deploy snapshotter command

- deploy/kubernetes/rbac.yaml
fix https://github.com/kubernetes-csi/external-snapshotter/issues/55
@xing-yang @jingxu97
> fix RABC rule

- OWNERS
My contributions so far:
https://github.com/kubernetes-csi/external-snapshotter/pulls/wackxu
My reviews so far:
https://github.com/kubernetes-csi/external-snapshotter/pulls?q=is%3Apr+is%3Aopen+reviewed-by%3Awackxu
I have also participate in review design of snapshotter and do some code implementation with @xing-yang. I have write test suite about snapshot in csi-test repo and unit test in this project. I have great interest in the snapshot and  I want to continue to  do some contributions.  And I have enough time to participate in the review work too.
@xing-yang @jingxu97
> add myself as approver for snapshotter

- README.md
- pkg/controller/csi_handler.go
- pkg/controller/snapshot_controller.go
- pkg/controller/snapshot_create_test.go
- pkg/controller/util.go
- pkg/controller/util_test.go
This PR cherry-picks adding new reserved prefixed parameter keys fix and a README update to release-1.0 branch.
> Cherry-pick adding new reserved prefixed parameter keys fix

- cmd/csi-snapshotter/main.go
- pkg/controller/framework_test.go
- pkg/controller/snapshot_controller.go
- pkg/controller/snapshot_controller_base.go
- pkg/controller/snapshot_create_test.go
> add pvcLister to snapshot controller

- pkg/apis/volumesnapshot/v1alpha1/types.go
- pkg/connection/connection.go
- pkg/controller/csi_handler.go
- pkg/controller/snapshot_controller.go
- pkg/controller/util.go
> Update exported function details with source code comments.

- README.md
> Correct markdown linter errors.

- deploy/kubernetes/setup-csi-snapshotter.yaml
This PR updates images in yaml files to v1.0.1.
> Update images to 1.0.1

- cmd/csi-snapshotter/create_crd.go
- cmd/csi-snapshotter/main.go
- pkg/connection/connection.go
- pkg/controller/framework_test.go
- pkg/controller/snapshot_controller.go
- pkg/controller/snapshot_controller_base.go
- pkg/controller/util.go
> Migrate to k8s.io/klog from glog.

- pkg/controller/framework_test.go
- pkg/controller/snapshot_controller.go
- pkg/controller/snapshot_ready_test.go
* Handle pre-bound snapshots for update.
> Fix for pre-bound snapshot empty source error

- deploy/kubernetes/rbac.yaml
- pkg/controller/framework_test.go
- pkg/controller/snapshot_controller.go
- pkg/controller/snapshot_finalizer_test.go
- pkg/controller/util.go
This PR adds Finalizer on the snapshot source PVC to prevent it
from being deleted when a snapshot is being created from it.
> Add Delete Volume Finalizer

- CHANGELOG-1.2.md
This PR adds changelog for the v1.2.1 release.
Fixes #
```release-note
NONE
```
> Add changelog for v1.2.1 release

- CHANGELOG-1.3.md
This PR adds changelog for release 1.3.
Fixes #
```release-note
NONE
```
> Add changelog for v1.3

- deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml
- deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
/kind cleanup
Update snapshot-controller and csi-snapshotter images to v2.0.0-rc2.
Fixes #
```release-note
NONE
```
> Update snapshot-controller and csi-snapshotter images to v2.0.0-rc2

- pkg/sidecar-controller/snapshot_controller.go
> Correct typo

- README.md
Updates README to reflect the actual code
```release-note
NONE
```
> Update README to reflect go module usage

- go.mod
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Fixes https://github.com/kubernetes-csi/external-snapshotter/pull/227#discussion_r362128723
```release-note
NONE
```
> Remove unnecessary csi-translation-lib dep

- CHANGELOG-2.1.md
Fixes #
```release-note
NONE
```
> Add changelog for 2.1.1 release

- pkg/common-controller/snapshot_controller.go
- pkg/sidecar-controller/snapshot_controller.go
- pkg/sidecar-controller/snapshot_delete_test.go
- pkg/utils/util.go
/kind cleanup
Fixes #
```release-note
```
> Remove unwanted code conditions

- README.md
- deploy/kubernetes/snapshot-controller/rbac-snapshot-controller.yaml
- deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
Make all namespace settings explicit and add more documentation around
setting appropriate namespace when installing.
/kind cleanup
Improves documentation around appropriate namespace setting for the snapshot controller. Makes all namespace settings in YAML files explicit.
Fixes #
```release-note
NONE
```
> Update docs for controller namespace

- pkg/snapshotter/snapshotter.go
/kind cleanup
Adjusts how we print the time stamp to correct unit test failures.
Fixes #
```release-note
NONE
```
> Adjusted the date printing to address unit test failure

- cmd/csi-snapshotter/main.go
- cmd/snapshot-controller/main.go
- go.mod
- pkg/common-controller/framework_test.go
- pkg/common-controller/snapshot_controller.go
- pkg/common-controller/snapshot_controller_base.go
- pkg/metrics/metrics.go
- pkg/sidecar-controller/framework_test.go
- pkg/sidecar-controller/snapshot_controller.go
- pkg/sidecar-controller/snapshot_controller_base.go
- pkg/snapshotter/snapshotter.go
- pkg/utils/util.go
/kind cleanup
Moves to klogv2
Fixes #
```release-note
NONE
```
> Move to klogv2

- deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml
- deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
/kind bug
Fixes #336 
```release-note
NONE
```
> Update controller images

- README.md
as the CRD directory is changed now, the readme should point to the new directory where the CRD is present.
Fixes #
```release-note
NONE
```
> update readme for new crd directory

- README.md
> Update the CSI spec support matrix

- CHANGELOG-2.1.md
Add change log for 2.1.2 release
Fixes #
```release-note
NONE
```
/cc @msau42
> Add change log for 2.1.2 release

- CHANGELOG/CHANGELOG-3.0.md
Create v3.0.1 change log
Fixes #
```release-note
NONE
```
/cc @msau42
> Create v3.0.1 change log

- cmd/csi-snapshotter/Dockerfile
- cmd/snapshot-controller/Dockerfile
- cmd/snapshot-validation-webhook/Dockerfile
>
/kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
> Cherry-pick #396: Fix the failing multiarch builds

- pkg/common-controller/snapshot_controller.go
/kind bug
Cherry-picking this change to release-3.0 branch as per @xing-yang's request. Original PR - https://github.com/kubernetes-csi/external-snapshotter/pull/413
Fixes #
```release-note
Bug fix to allow creation of snapshot content if pvc finalizer exists, even if pvc is marked for deletion.
```
> Cherry pick #413 to release-3.0

- CHANGELOG/CHANGELOG-3.0.md
Fixes #
```release-note
NONE
```
> Add changelog for 3.0.2

- CHANGELOG/CHANGELOG-3.0.md
/kind cleanup
This PR fixes the PR number referenced in changelog.
Fixes #
```release-note
NONE
```
> Fix the changelog

- README.md
- cmd/csi-snapshotter/main.go
- cmd/snapshot-controller/main.go
/kind cleanup
Increase resync-period default to 15mins 
Fixes #444
n/a
```release-note
Increased the default re-sync period to 15 minutes for the snapshotter sidecar and snapshot controller. 
```
> Increase resync-period default to 15 minutes

- CHANGELOG/CHANGELOG-3.0.md
- deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml
- deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
- deploy/kubernetes/webhook-example/webhook.yaml
/kind cleanup
Update snapshot-controller image to pass CI.
Fixes #
```release-note
NONE
```
> Update snapshot-controller image to 3.0.3

- CHANGELOG/CHANGELOG-4.0.md
Fixes #
```release-note
NONE
```
> Add changelog for release 4.0

- README.md
Fixes #
```release-note
NONE
```
> Clarify instructions about validation webhook

- CHANGELOG/CHANGELOG-3.0.md
Updates changelog for v3.0.3.
Fixes #
```release-note
NONE
```
> Update changelog for 3.0.3 release

- .prow.sh
- release-tools/build.make
- release-tools/prow.sh
We want to test also older branches on Kubernetes 1.20.
Fixes #472 
```release-note
NONE
```
> support testing on Kubernetes 1.20

- CHANGELOG-2.1.md
Fixes #
```release-note
NONE
```
> Add changelog for v1.2.4

- deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
>
Update in the reference implementation yaml for #504, added some properties to the `RollingUpdate` strategy
```release-note
NONE
```
/assign @msau42 @verult
> Update reference implementation of the snapshot controller

- cmd/snapshot-controller/main.go
/kind bug
Fixes https://github.com/kubernetes-csi/external-snapshotter/pull/506#discussion_r623368950
```release-note
NONE
```
/assign @xing-yang
> Fix typo in CRD check

- CHANGELOG/CHANGELOG-4.1.md
- README.md
Fixes #
```release-note
NONE
```
> Add changelog for 4.1.0

- CHANGELOG/CHANGELOG-4.1.md
- README.md
Fix the compatibility table in README
Fixes #
```release-note
NONE
```
> Fix the compatibility table in README

- cmd/snapshot-controller/main.go
/kind bug
Updates the v1 volumesnapshots CRD check to list resources across all namespaces
Fixes #514 
```release-note
NONE
```
/cc @xing-yang @msau42
> Update volumesnapshots request to list across all namespaces

- CHANGELOG/CHANGELOG-4.1.md
Fixes #
```release-note
NONE
```
> Changelog 4.1.1

- deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml
- deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
- deploy/kubernetes/webhook-example/webhook.yaml
update setup-csi-snapshotter.yaml csi-snapshotter image from v4.0.0 to v4.1.1
> update setup-csi-snapshotter.yaml csi-snapshotter image 

- deploy/kubernetes/webhook-example/README.md
>
> /kind bug
> /kind design
> /kind flake
**What this PR does / why we need it**: I encountered some faulty pathnames while going through the Readme, PTAL.
Fixes #
```release-note
NONE
```
> Fix some pathnames

- pkg/metrics/metrics.go
- pkg/metrics/metrics_test.go
/kind feature
Adds an operations in flight metrics to find any leaky operations in our metrics implementation. If a snapshot is not in progress, and in flight metrics are >0, we have a leak. I've done some basic testing with this metric and haven't found any leaked operations yet.
Fixes #434 
I decided to change the sync.Map to be a normal map with a RWMutex. This is because sync.Map does not allow the user to find its length (golang/go issue 20680).
The original issue calls to check for any built-in way to determine if we have leaked operations. Except for some pprof memory profiling, I didn't see …
> Add gauge metric for snapshot controller operations in flight

- README.md
/kind cleanup
Fixes an issue in the README where the recommended Kubernetes version is set to one higher than it should be.
See for more details:
https://kubernetes-csi.github.io/docs/project-policies.html#recommended-version
Fixes #
```release-note
NONE
```
/assign @xing-yang
> Fix recommended Kubernetes version in README

- go.mod
- go.sum
- vendor/github.com/kubernetes-csi/csi-lib-utils/connection/connection.go
- vendor/github.com/kubernetes-csi/csi-lib-utils/metrics/metrics.go
- vendor/modules.txt
/kind feature
Updates csi-lib-utils to v0.10.0.
Fixes #
```release-note
Updates csi-lib-utils dependency to v0.10.0
```
/assign @xing-yang
> Use csi-lib-utils v0.10.0

- CHANGELOG/CHANGELOG-4.2.md
- README.md
- deploy/kubernetes/csi-snapshotter/rbac-external-provisioner.yaml
- deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml
- deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
- deploy/kubernetes/webhook-example/webhook.yaml
Added changelog for v4.2.
Also removed "metrics-address" for snapshot-controller from README. This option was never added to snapshot-controller.
Fixes #
```release-note
NONE
```
> Add changelog for 4.2

- CHANGELOG/CHANGELOG-4.2.md
Fixes #
```release-note
NONE
```
> Add changelog for 4.2.1

- deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml
- deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
- deploy/kubernetes/webhook-example/webhook.yaml
Update images to v4.2.1.
Fixes #
```release-note
NONE
```
> Update images to v4.2.1

- pkg/metrics/metrics.go
- pkg/metrics/metrics_test.go
>
/kind bug
> /kind design
> /kind flake
Fixes #
The intention is to create a new patch version for 4.1 release branch
If approved, similar cherry pick will be submitted to 4.2 branch as well.
```release-note
Add process_start_time_seconds metric
```
> Cherrypick #569 to 4.1 branch

- deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml
- deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
/kind cleanup
Needed to make tests pass
n/a
n/a
```release-note
NONE
```
> Bump snapshot-controller and snapshotter deploy to v5-rc1

- README.md
- client/config/crd/kustomization.yaml
- deploy/kubernetes/csi-snapshotter/kustomization.yaml
- deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml
- deploy/kubernetes/snapshot-controller/kustomization.yaml
>
> /kind bug
> /kind design
> /kind flake
/kind design
I've been asked to backport the changes merged in #606 to the release-5.0 branch: https://github.com/kubernetes-csi/external-snapshotter/pull/606#issuecomment-982086780
Fixes #605
none
```release-note
Cherry-pick #606: Added kustomization manifests to CRDs and controller components
```
> Backport #606 to release-5.0

- deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml
/kind cleanup
Rename KUBE_NODE_NAME to NODE_NAME, no need to use both of them.
Fixes #615 
@xing-yang
```release-note
Rename KUBE_NODE_NAME to NODE_NAME
```
> Rename KUBE_NODE_NAME to NODE_NAME

- README.md
- cmd/csi-snapshotter/main.go
- cmd/snapshot-controller/main.go
- deploy/kubernetes/snapshot-controller/rbac-snapshot-controller.yaml
- go.mod
- go.sum
- pkg/common-controller/framework_test.go
- pkg/common-controller/snapshot_controller.go
- pkg/common-controller/snapshot_controller_base.go
- pkg/common-controller/snapshot_controller_test.go
- pkg/utils/util.go
- vendor/k8s.io/component-helpers/LICENSE
- vendor/k8s.io/component-helpers/scheduling/corev1/doc.go
- vendor/k8s.io/component-helpers/scheduling/corev1/helpers.go
- vendor/k8s.io/component-helpers/scheduling/corev1/nodeaffinity/nodeaffinity.go
- vendor/modules.txt
>
> /kind bug
> /kind design
/kind feature
> /kind flake
Backporting changes from #585   to release-5.0 
Fixes #
```release-note
Cherry-pick #585: Adds support for distributed snapshotting.
```
> Backport #585 to release 5.0

- CHANGELOG/CHANGELOG-5.0.md
- deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml
- deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
- deploy/kubernetes/webhook-example/webhook.yaml
This PR adds changelog for v5.0.0 and updates image versions.
Fixes #
```release-note
NONE
```
> Add changelog for v5.0.0

- CHANGELOG/CHANGELOG-5.0.md
- deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml
- deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
- deploy/kubernetes/webhook-example/webhook.yaml
Backports PR #635 (changelog for v5.0.0 and update images) to release-5.0 branch.
Fixes #
```release-note
NONE
```
> Backport changelog to release-5.0

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/enhancement.md
- .github/ISSUE_TEMPLATE/support.md
doc: add issue templates, copied from nfs csi driver.
Fixes #
```release-note
none
```
> doc: add issue templates

- deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml
- deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
- deploy/kubernetes/webhook-example/webhook.yaml
Signed-off-by: Abhishek Jain <abjain39@in.ibm.com>
>
/kind bug
> /kind design
> /kind flake
This PR fixes issue 649. It changes the snapshot controller image version in the setup script to v5.0.1.
Fixes #649 
```release-note
None
```
> Change snapshot controller image version to 5.0.1

- CHANGELOG/CHANGELOG-4.0.md
What type of PR is this?
What this PR does / why we need it: Changelog for patch release 4.0.1
Which issue(s) this PR fixes:
Fixes #
Special notes for your reviewer:
Does this PR introduce a user-facing change?:
```
NONE
```
> Add changelog for 4.0.1

- .github/workflows/codespell.yml
- CHANGELOG/CHANGELOG-3.0.md
- client/apis/volumesnapshot/v1/types.go
- client/config/crd/snapshot.storage.k8s.io_volumesnapshots.yaml
- deploy/kubernetes/webhook-example/create-cert.sh
doc: fix spelling issues and add codespell github action
I am enforcing codespell github action in one CSI driver, and found there are spelling issues in snapshot CRDs
Fixes #
```release-note
none
```
> doc: fix spelling issues and add codespell github action

- pkg/sidecar-controller/snapshot_controller_base.go
/kind bug
After creating a snapshot, external-snapshotter needs to wait for a VolumeSnapshotContent to be ready. This re-adds logic (removed in #651) to enqueue a VolumeSnapshotContent after it has been updated, as long as there wasn't an error encountered in creating (or updating) the snapshot. Effectively this allows the controller to continuously poll the VolumeSnapshotContent until it is ready.
Fixes #533 
```release-note
Ensure that the CSI snapshotter sidecar allows for CreateSnapshot retries while waiting for a snapshot to be ready.
```
> Allow resync on VolumeSnapshotContent when there is no error from CreateSnapshot

- deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml
- deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
- deploy/kubernetes/webhook-example/webhook.yaml
Signed-off-by: Abhishek Jain <abjain39@in.ibm.com>
>
kind bug
> /kind design
> /kind flake
Fixes #
```release-note
Cherrypick #653: Change snapshot controller image version to 5.0.1
```
> Cherrypick #653 to release-5.0 branch

- README.md
README changes to add `prevent-volume-mode-conversion`
Fixes #
```release-note
```
> Update README with prevent-volume-mode-conversion feature flag

- .github/workflows/trivy.yaml
test: add tirvy vulnerability scanner github action
as discussed in https://github.com/kubernetes-csi/livenessprobe/pull/149#issuecomment-1128413164
Fixes #
```release-note
none
```
> test: add tirvy vulnerability scanner github action

- README.md
Cherry pick of https://github.com/kubernetes-csi/external-snapshotter/pull/702/files
Fixes #
```release-note
```
> README changes to release-6.0 branch

- deploy/kubernetes/webhook-example/README.md
- examples/kubernetes/invalid-snapshot-v1beta1.yaml
- examples/kubernetes/snapshot-v1beta1.yaml
- examples/kubernetes/snapshotclass-v1beta1.yaml
/kind cleanup
Remove VolumeSnapshot v1beta1 examples.
Cleanup README for validation webhook.
Fixes #
```release-note
NONE
```
> Remove v1beta1 examples

- CHANGELOG/CHANGELOG-6.0.md
**What type of PR is this?**:
Fixes #
```release-note
NONE
```
> Add changelog for v6.0

- deploy/kubernetes/webhook-example/README.md
- examples/kubernetes/invalid-snapshot-v1beta1.yaml
- examples/kubernetes/snapshot-v1beta1.yaml
- examples/kubernetes/snapshotclass-v1beta1.yaml
(cherry picked from commit c821877a2e95692dec42024871a6cd4979f5c5c3)
/kind cleanup
Backport #715 
Fixes #
```release-note
NONE
```
> Backport 715: Remove v1beta1 examples

- CHANGELOG/CHANGELOG-6.0.md
(cherry picked from commit 14a0e296359d4b654828e0c1a0f8bc4fbacf0757)
Fixes #
```release-note
NONE
```
> Backport 711: Add changelog for v6.0

- CHANGELOG/CHANGELOG-6.0.md
(cherry picked from commit 35e3db53d357df17370afcb32ca20031ec97a445)
Cherry-picks #720 
Fixes #
```release-note
NONE
```
> Backport 720: Update changelog 6.0.1

- go.mod
- vendor/modules.txt
> update snapshot client to v6.0.1

- go.mod
- go.sum
- vendor/golang.org/x/net/context/go17.go
- vendor/golang.org/x/net/http2/frame.go
- vendor/golang.org/x/net/http2/hpack/encode.go
- vendor/golang.org/x/net/http2/hpack/hpack.go
- vendor/golang.org/x/net/http2/http2.go
- vendor/golang.org/x/net/http2/server.go
- vendor/golang.org/x/net/http2/transport.go
- vendor/golang.org/x/sys/unix/syscall_aix.go
- vendor/modules.txt
This commit address above mentioned CVE
> /kind bug
```release-note
NONE
```
> Fix CVE-2022-27664 by updating golang.org/x/net pacckage

- CHANGELOG/CHANGELOG-6.1.md
Add changelog for v6.1.0.
Fixes #
```release-note
NONE
```
> Add changelog for v6.1.0

- go.mod
- vendor/modules.txt
/kind cleanup
This PR updates the client dep to v6.1.0.
Fixes #
```release-note
Update the external-snapshotter client dep to v6.1.0.
```
> Update client to v6.1.0

- deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml
- deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
- deploy/kubernetes/webhook-example/webhook.yaml
/kind cleanup
This PR updates the tag of snapshotter deployment YAMLs to `v6.1.0`.
Note that these images do not exist yet, they will be created when the release is cut. 
Fixes #
```release-note
Update deployment tags to v6.1.0
```
> Update deployment tags to v6.1.0

- deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml
- deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
- deploy/kubernetes/webhook-example/webhook.yaml
Signed-off-by: Abhishek Jain <abjain39@in.ibm.com>
>
/kind bug
> /kind design
> /kind flake
Fixes #750
```release-note
None
```
> change snapshot controller image version to 6.0.1 in release-6.0 branch

- deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml
> update sidecars to latest version

- .github/workflows/codespell.yml
- .github/workflows/trivy.yaml
test: fix trivy and codespell github action failure
Fixes #
```release-note
none
```
> test: fix trivy and codespell github action failure

- CHANGELOG/CHANGELOG-6.2.md
Adds changelog for v6.2.0.
Fixes #
This changelog is generated based on this PR: https://github.com/kubernetes-csi/external-snapshotter/pull/801
```release-note
NONE
```
> Add changelog for v6.2.0

- deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml
- deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
- deploy/kubernetes/webhook-example/webhook.yaml
/kind cleanup
Fixes #808 
```release-note
NONE
```
> Update images to v6.2.1

- deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml
- deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
- deploy/kubernetes/webhook-example/webhook.yaml
>
/kind bug
> /kind design
> /kind flake
Fixes #
```release-note
Cherrypick #809: Change snapshot controller image version to 6.2.1
```
> Change snapshot controller image version to 6.2.1 in release-6.2 branch

- release-tools/build.make
- release-tools/cloudbuild.yaml
/kind cleanup
Fixes #
```release-note
NONE
```
> Update csi-release-tools 

- .github/workflows/dependabot.yaml
- .github/workflows/trivy.yaml
- client/config/crd/kustomization.yaml
- deploy/kubernetes/csi-snapshotter/kustomization.yaml
- deploy/kubernetes/csi-snapshotter/rbac-csi-snapshotter.yaml
- deploy/kubernetes/csi-snapshotter/rbac-external-provisioner.yaml
- deploy/kubernetes/snapshot-controller/kustomization.yaml
- deploy/kubernetes/snapshot-controller/rbac-snapshot-controller.yaml
- deploy/kubernetes/webhook-example/rbac-snapshot-webhook.yaml
- deploy/kubernetes/webhook-example/webhook.yaml
- examples/kubernetes/invalid-snapshot-v1.yaml
- examples/kubernetes/pvc.yaml
- examples/kubernetes/restore.yaml
- examples/kubernetes/snapshot-v1.yaml
- examples/kubernetes/snapshotclass-v1.yaml
- examples/kubernetes/storageclass.yaml
/kind cleanup
The YAML Specification requires three daashes `---` as marker for the start of a content block. That means, each YAML file needs to start with `---` on the first line (or after initial comments).
See-also: https://yaml.org/
Fixes #455
Some files under `vendor/` and `release-tools/` have not been updated.
```release-note
NONE
```
> add "document-start" 1st line to all yaml files

- release-tools/SIDECAR_RELEASE_PROCESS.md
> release tools update

- cmd/csi-snapshotter/main.go
- cmd/snapshot-controller/main.go
/kind feature
Disable the flag for now. Will enable it when the feature is fully implemented.
Fixes #
```release-note
Disable the enable-volume-group-snapshots feature flag.
```
> Disable VolumeGroupSnapshot feature flag

- go.mod
- vendor/modules.txt
/kind cleanup
Update snapshotter client lib version to 6.3.0.
Fixes #
```release-note
NONE
```
> Update client lib version to 6.3.0

- deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml
- deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
- deploy/kubernetes/webhook-example/webhook.yaml
>
/kind bug
> /kind design
> /kind flake
Fixes #
```release-note
None
```
> Change snapshot controller image version to 6.2.2 in release-6.2 branch

- CHANGELOG/CHANGELOG-6.0.md
Fixes #
```release-note
NONE
```
> Add changelog for v6.0.1

- CHANGELOG/CHANGELOG-6.2.md
Fixes #
```release-note
NONE
```
> Add changelog for v6.2.3

- CHANGELOG/CHANGELOG-6.3.md
Fixes #
```release-note
NONE
```
> Add Changelog for v6.3.1

- deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml
- deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
- deploy/kubernetes/webhook-example/webhook.yaml
> Snapshot controller deployment update

- deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml
- deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
- deploy/kubernetes/webhook-example/webhook.yaml
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Fixes #
```release-note
None
```
> Change snapshot controller image version to 6.2.3 in release-6.2 branch

- deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml
- deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
- deploy/kubernetes/webhook-example/webhook.yaml
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Fixes #
```release-note
None
```
> Change snapshot controller image version to 6.3.1 in release-6.3 branch

- CHANGELOG/CHANGELOG-6.3.md
Add changelog for v6.3.2
Fixes #
```release-note
NONE
```
> Add changelog for v6.3.2

- CHANGELOG/CHANGELOG-6.3.md
> Changelog for v6.3.3

- CHANGELOG/CHANGELOG-7.0.md
Fixes #
```release-note
NONE
```
> Add changelog 7.0

- CHANGELOG/CHANGELOG-7.0.md
Fixes #
```release-note
NONE
```
> Add changelog 7.0.1

- CHANGELOG/CHANGELOG-6.3.md
> Changelog for v6.3.4

- CHANGELOG/CHANGELOG-7.0.md
> Changelog for v7.0.2

- pkg/common-controller/groupsnapshot_controller_helper.go
- pkg/sidecar-controller/groupsnapshot_helper.go
- pkg/utils/util.go
Fixes: https://github.com/kubernetes-csi/external-snapshotter/issues/834
Signed-off-by: Manish <myathnal@redhat.com>
(cherry picked from commit e171a982681be29556ca46c06ea6378cdfe3effe)
>
/kind bug
> /kind design
> /kind flake
Fixes #
```release-note
Cherry-pick from PR [#1034](https://github.com/kubernetes-csi/external-snapshotter/pull/1034) Adds secret reference to volume group snapshot …
```
> [release-7.0] Add snapshot secret reference to group snapshot controller.

- deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml
- deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
- deploy/kubernetes/webhook-example/webhook.yaml
>
> /kind bug
/kind design
> /kind flake
Use the latest controller image version in the deployment scripts
Fixes #
```release-note
```
> Update controller deployment to latest version

- release-tools/SIDECAR_RELEASE_PROCESS.md
- release-tools/build.make
- release-tools/generate-patch-release-notes.sh
- release-tools/go-modules-targeted-update.sh
- release-tools/prow.sh
- release-tools/verify-logcheck.sh
- vendor/github.com/kubernetes-csi/external-snapshotter/client/v7/apis/volumegroupsnapshot/v1alpha1/types.go
- vendor/github.com/kubernetes-csi/external-snapshotter/client/v7/apis/volumesnapshot/v1/types.go
/kind cleanup
This PR updates release-tools.
```
Squashed 'release-tools/' changes from dc4d0ae2..edd89ad5
edd89ad5 Merge pull request #251 from jsafrane/add-logcheck
043fd099 Add test-logcheck target
d7535ae0 Merge pull request #250 from jsafrane/go-1.22
b52e7ad3 Update go to 1.22.2
14fdb6f6 Merge pull request #247 from msau42/prow
9b4352e9 Update release playbook
c7bb972c Fix release notes script to use fixed tags
463a0e9f Add script to update specific go modules
git-subtree-split: edd89ad58509b16d1a1fbdfe1d2d935beb36c67a
```
Fixes #
```release-note
NONE
```
> Update release tools

- CHANGELOG/CHANGELOG-8.0.md
> Changelog for v8.0.1

- .github/workflows/codespell.yml
- .github/workflows/trivy.yaml
- release-tools/.github/dependabot.yaml
- release-tools/.github/workflows/codespell.yml
- release-tools/.github/workflows/trivy.yaml
- release-tools/SIDECAR_RELEASE_PROCESS.md
- release-tools/generate-patch-release-notes.sh
chore: update release-tools to fix spelling error
```
Squashed 'release-tools/' changes from https://github.com/kubernetes-csi/external-snapshotter/commit/adb3af9dfa3ed4d1a922cd839bb48e0b73918617..https://github.com/kubernetes-csi/external-snapshotter/commit/f40f0ccd458f2d4555e3ca98d69b5a984bae0f14
https://github.com/kubernetes-csi/external-snapshotter/commit/f40f0ccd458f2d4555e3ca98d69b5a984bae0f14 Merge pull request https://github.com/kubernetes-csi/external-snapshotter/pull/256 from solumath/master
https://github.com/kubernetes-csi/external-snapshotter/commit/cfa92106cd9eac6b51e9257b71296a84cc03dbaf Instruction update
https://github.com/kubernetes-csi/external-snapshotter/commit/379a1bb9b001c0d62a091 …
```
> chore: update release-tools to fix spelling error

- release-tools/prow.sh
kind cleanup
cleanup: Update csi release tools
Fixes #
```release-note
cleanup: Update csi release tools 
```
> cleanup: Update csi release tools

- pkg/metrics/metrics.go
/kind bug
When running unit tests with `-race` there is one go routine leaking. This PR fixes the leak.
```release-note
NONE
```
> Fix scheduleOpsInFlightMetric go routine leak

- CHANGELOG/CHANGELOG-8.1.md
Update changelog v8.1.0
```release-note
NONE
```
> Create changelog v8.1.0

- pkg/common-controller/framework_test.go
- pkg/utils/util.go
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Removed the unused labels and test code
Fixes #1206 
```release-note
None
```
> remove unused labels from util

- .github/workflows/trivy.yaml
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
actions/setup-go@v5 supports using go.mod to install the required version of golang, if any changes are required specific to version we dont need to make changes in 2 places.
Fixes #
```release-note
None
```
> ci: use go version from go.mod for trivy

- client/config/crd/groupsnapshot.storage.k8s.io_volumegroupsnapshotclasses.yaml
- client/config/crd/groupsnapshot.storage.k8s.io_volumegroupsnapshotcontents.yaml
- client/config/crd/groupsnapshot.storage.k8s.io_volumegroupsnapshots.yaml
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Fixes #
```release-note
The `api-approved.kubernetes.io` annotation on the VolumeGroupSnapshot, VolumeGroupSnapshotContent, and VolumeGroupSnapshotClass CRD now point to the PR introducing v1beta1
```
> Update the API Approved Annotation for volume group snapshots

- CHANGELOG/CHANGELOG-8.2.md
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
> Add release notes for v8.2.0

- CHANGELOG/CHANGELOG-8.0.md
>
> /kind bug
> /kind design
> /kind flake
Fixes #
Canary tests: https://testgrid.k8s.io/sig-storage-csi-ci
image push tests: https://testgrid.k8s.io/sig-storage-image-build#post-external-snapshotter-push-images
```release-note
NONE
```
> Add changelog for 8.0.2

- CHANGELOG/CHANGELOG-8.1.md
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
> Add changelog for 8.1.1

- deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml
- deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
- deploy/kubernetes/webhook-example/webhook.yaml
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Update `/deploy` directory with latest version so [README usage](https://github.com/kubernetes-csi/external-snapshotter/tree/master?tab=readme-ov-file#usage) instructions work for this release branch. 
Fixes #
```release-note
NONE
```
> Update deployment with v8.0.2

- deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml
- deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Update `/deploy` directory with latest version so [README usage](https://github.com/kubernetes-csi/external-snapshotter/tree/master?tab=readme-ov-file#usage) instructions work. 
Fixes #
```release-note
NONE
```
> Update deployment to v8.2.0

- deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml
- deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
- deploy/kubernetes/webhook-example/webhook.yaml
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Update deployment with v8.1.1 so operators can follow README.md instructions to install snapshot controller to their cluster. 
Fixes #
```release-note
NONE
```
> Update deployment with v8.1.1

- README.md
**What this PR does / why we need it**: Updates the docs around install commands to clarify these are copy/paste command lines, and add remote kustomize commands for ease of use.
**Which issue(s) this PR fixes**: None opened.
**Special notes for your reviewer**: N/A
```release-note
NONE
```
> docs: update install commands for CRDs + snapshotter

- deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml
- deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Backports 2d6e908feffe8fc5da71a8dd0f95bf4212521a9c [#1245] to `release-8.2`
```release-note
NONE
```
> Update deployment to v8.2.0 (backport on release-8.2)

- CHANGELOG/CHANGELOG-8.3.md
- go.mod
>
> /kind bug
> /kind design
> /kind flake
Adds changelog for v8.3.0.
Fixes #
This is submitted on top of https://github.com/kubernetes-csi/external-snapshotter/pull/1310 which should be merged first.
```release-note
NONE
```
> Add Changelog for v8.3.0
